data = expss::apply_labels(data,CDDEATHP = c(" No, death not during pregnancy, childbirth, or 42 days or 1 year of end of p " = 1, " Yes, during pregnancy " = 2, " Yes, during childbirth " = 3, " Yes, within 42 days of end of pregnancy " = 4, " Yes, between 43 days and 1 year of end of pregnancy " = 5),
Q1001A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q1001B = c(" Yes " = 1, " No " = 2),
Q1002AD = c(" Day not recorded " = 98),
Q1002AM = c(" January " = 1, " February " = 2, " March " = 3, " April " = 4, " May " = 5, " June " = 6, " July " = 7, " August " = 8, " September " = 9, " October " = 10, " November " = 11, " December " = 12, " Month not recorded " = 98),
Q1002AY = c(" Year not recorded " = 9998),
Q1002BD = c(" Day not recorded " = 98),
Q1002BM = c(" January " = 1, " February " = 2, " March " = 3, " April " = 4, " May " = 5, " June " = 6, " July " = 7, " August " = 8, " September " = 9, " October " = 10, " November " = 11, " December " = 12, " Month not recorded " = 98),
Q1002BY = c(" Year not recorded " = 9998),
Q1003A = c(" Cause of death (first line) " = 6),
Q1003B = c(" Cause of death (second line) " = 6),
Q1003C = c(" Cause of death (third line) " = 6),
Q1003D = c(" Cause of death (fourth line) " = 6),
Q1004A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q1004B = c(" Yes " = 1, " No " = 2),
Q1005D = c(" Day not recorded " = 98),
Q1005M = c(" January " = 1, " February " = 2, " March " = 3, " April " = 4, " May " = 5, " June " = 6, " July " = 7, " August " = 8, " September " = 9, " October " = 10, " November " = 11, " December " = 12, " Month not recorded " = 98),
Q1005Y = c(" Year not recorded " = 9998),
Q1006 = c(" Cause of death from the burial permit " = 6),
Q101D = c(" Don t know day " = 98),
Q101F = c(" Ruled ineligible for survey " = 0, " Month and year " = 1, " Month and age -y imp " = 2, " Year and age - m imp " = 3, " Y & age - y ignored " = 4, " Year - a, m imp " = 5, " Age - y, m imp " = 6, " Month - a, y imp " = 7, " None - all imp " = 8),
Q101M = c(" January " = 1, " February " = 2, " March " = 3, " April " = 4, " May " = 5, " June " = 6, " July " = 7, " August " = 8, " September " = 9, " October " = 10, " November " = 11, " December " = 12, " Don t know month " = 98),
Q102D = c(" Don t know day " = 98),
Q102F = c(" Ruled ineligible for survey " = 0, " M of death and Y of death " = 1, " Y of death, Age of Death, Y of Birth, M of Birth - M of death imputed " = 2, " Y of death, Age of death, Year of birth - M of death imputed " = 3, " Y of death, Age of death, M of birth - M of death imputed " = 4, " Y of death, Age of death - M of death imputed " = 5, " Y of deah - M of death imputed " = 6, " None - Y of death, M of death imputed " = 7, " Other " = 8),
Q102M = c(" January " = 1, " February " = 2, " March " = 3, " April " = 4, " May " = 5, " June " = 6, " July " = 7, " August " = 8, " September " = 9, " October " = 10, " November " = 11, " December " = 12, " Don t know month " = 98),
Q104 = c(" 95 or more " = 95),
Q106 = c(" Yes " = 1, " No " = 2),
Q107 = c(" Yes " = 1, " No " = 2),
Q108A = c(" Yes " = 1, " No " = 2),
Q108C = c(" Yes " = 1, " No " = 2),
Q108D = c(" Yes " = 1, " No " = 2),
Q109 = c(" Never married " = 1, " Married " = 2, " Living with a partner " = 3, " Separated " = 4, " Divorced " = 5, " Widowed " = 6),
Q110 = c(" Primary " = 1, " Middle " = 2, " Jss/jhs " = 3, " Secondary/Tech/Voc/Comm " = 4, " Sss/Shs/Tech/Voc/Comm " = 5, " Higher " = 6, " Never attended school " = 7, " Don t know " = 8),
Q111 = c(" Yes " = 1, " No " = 2),
Q112 = c(" Commissioned armed forces officers " = 1, " Non-commissioned armed forces officers " = 2, " Armed forces occupations, other ranks " = 3, " Chief executive, senior officers and legislators " = 11, " Administrative and commercial managers " = 12, " Production and specialized service managers " = 13, " Hospitality, retail and other services managers " = 14, " Science and engineering professionals " = 21, " Health professionals " = 22, " Teaching professionals " = 23, " Business and administrative professionals " = 24, " Information and communication technology professionals " = 25, " Legal, social and cultural professional " = 26, " Science and engineering associate professionals " = 31, " Health associate professionals " = 32, " Business and administration associate professionals " = 33, " Legal, social cultural and related associate professionals " = 34, " Information and communications technicians " = 35, " General and keyboard clerks " = 41, " Customer service clerks " = 42, " Numerical and mateial recording clerks " = 43, " Other clerical support workers " = 44, " Personal sales workers " = 51, " Sales workers " = 52, " Personal care workers " = 53, " Market-oriented agricultural workers " = 61, " Market-oriented skilled forestry, fishery and hunting workers " = 62, " Subsistence farmers, fishers, hunters and gatherers " = 63, " Building and related trades workers, excluding electricians " = 71, " Metal, machinery and related trades workers " = 72, " Handicraft and printing workers " = 73, " Electrical and electronic trades workers " = 74, " Food processing, wood working, garment and other craft and related trades w " = 75, " Stationary plant and machine operators " = 81, " Assemblers " = 82, " Drivers and mobile plant operators " = 83, " Cleaners and helpers " = 91, " Agricultural, forestry and fishery labourers " = 92, " Labours in mining, construction, manufacturing and transport " = 93, " Food preparation assistants " = 94, " Street and related sales and service workers " = 95, " Refuse workers and other elementary workers " = 96, " Other occupations " = 97),
Q113 = c(" Catholic " = 1, " Anglican " = 2, " Methodist " = 3, " Presbyterian " = 4, " Pentecostal/charismatic " = 5, " Other christian " = 6, " Islam " = 7, " Traditional/spiritualist " = 8, " No religion " = 9, " Other " = 96, " Don t know " = 98),
Q114 = c(" Akan " = 1, " Ga/dangme " = 2, " Ewe " = 3, " Guan " = 4, " Mole-dagbani " = 5, " Grusi " = 6, " Gurma " = 7, " Mande " = 8, " Other " = 96),
Q115 = c(" Her home " = 1, " Other home " = 2, " Health facility " = 3, " En route to health facility " = 4, " Shrine/prayer camp " = 5, " Other " = 6),
Q116 = c(" In this house " = 1, " In this locality " = 2, " In a different village/town " = 3, " Other " = 6),
Q117 = c(" In this house " = 1, " In this locality " = 2, " In a different village/town " = 3, " Burial not yet performed " = 4, " Other " = 6),
Q118 = c(" Wet season " = 1, " Dry season " = 2, " Other " = 6),
Q119 = c(" Husband/partner " = 1, " Parent " = 2, " Child " = 3, " Sibling " = 4, " Other family member " = 5, " Friend " = 6, " Another relationship " = 7),
Q120 = c(" Yes " = 1, " No " = 2),
Q201 = c(" Narrative events " = 6),
Q301 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q302A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q302B = c(" Pedestrian " = 1, " Driver or passenger in car or light vehicle " = 2, " Driver or passenger in bus or heavy vehicle " = 3, " Driver or passenger on motorcycle " = 4, " Driver or passenger on pedal cycle " = 5, " Other " = 6, " Don t know " = 8),
Q303 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q304 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q305 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q306 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q307A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q307B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q307C = c(" Dog " = 1, " Snake " = 2, " Insect " = 3, " Scorpion " = 4, " Other " = 6, " Don t know " = 8),
Q308 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q309 = c(" Yes, suicide " = 1, " Yes, homicide " = 2, " Yes, abuse " = 3, " No " = 4, " Don t know " = 8),
Q310 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q311 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q312 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q313 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q314 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q315 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q316 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q317 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q318 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q319 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q401AN = c(" 95 or more " = 95),
Q401AU = c(" Days " = 1, " Weeks " = 2, " Months " = 3, " Years " = 4),
Q402 = c(" Yes " = 1, " No " = 2),
Q403 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q404N = c(" 95 or more " = 95, " Don t know " = 98),
Q404U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q405A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q405BN = c(" 95 or more " = 95, " Don t know " = 98),
Q405BU = c(" Days " = 1, " Weeks " = 2, " Months " = 3, " Special answers " = 9),
Q406 = c(" Positive " = 1, " Negative " = 2, " Don t know " = 8),
Q407 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q408N = c(" 95 or more " = 95, " Don t know " = 98),
Q408U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q409 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q410A = c(" Positive " = 1, " Negative " = 2, " Don t know " = 8),
Q410BN = c(" 95 or more " = 95, " Don t know " = 98),
Q410BU = c(" Days " = 1, " Weeks " = 2, " Months " = 3, " Special answers " = 9),
Q413 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q414N = c(" 95 or more " = 95, " Don t know " = 98),
Q414U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q415 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q416N = c(" 95 or more " = 95, " Don t know " = 98),
Q416U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q417 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q418N = c(" 95 or more " = 95, " Don t know " = 98),
Q418U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q419 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q420N = c(" 95 or more " = 95, " Don t know " = 98),
Q420U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q421 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q422N = c(" 95 or more " = 95, " Don t know " = 98),
Q422U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q423 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q424N = c(" 95 or more " = 95, " Don t know " = 98),
Q424U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q425 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q426 = c(" Lung " = 11, " Breast " = 12, " Cervix " = 13, " Liver " = 14, " Throat " = 15, " Colon " = 16, " Other " = 96, " Don t know " = 98),
Q427N = c(" 95 or more " = 95, " Don t know " = 98),
Q427U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q428 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q429N = c(" 95 or more " = 95, " Don t know " = 98),
Q429U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q430 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q431N = c(" 95 or more " = 95, " Don t know " = 98),
Q431U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q432 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q433N = c(" 95 or more " = 95, " Don t know " = 98),
Q433U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q434 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q435 = c(" Bipolar disorder " = 1, " Schizophrenia " = 2, " Other " = 6, " Don t know " = 8),
Q436N = c(" 95 or more " = 95, " Don t know " = 98),
Q436U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q437 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q438N = c(" 95 or more " = 95, " Don t know " = 98),
Q438U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q439 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q440N = c(" 95 or more " = 95, " Don t know " = 98),
Q440U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q441 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q442N = c(" 95 or more " = 95, " Don t know " = 98),
Q442U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q443 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q444N = c(" 95 or more " = 95, " Don t know " = 98),
Q444U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q445 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q446 = c(" Lupus " = 1, " Rheumatoid arthritis " = 2, " Other " = 6, " Don t know " = 8),
Q447N = c(" 95 or more " = 95, " Don t know " = 98),
Q447U = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q448 = c(" Cause of death " = 6),
Q501A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q501B = c(" 95 or more " = 95, " Don t know " = 98),
Q501C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q501D = c(" Mild " = 1, " Moderate " = 2, " Severe " = 3),
Q501E = c(" Continuous " = 1, " On and off " = 2, " Only at night " = 3, " Only during day " = 4, " Don t know " = 8),
Q501F = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q502A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q502BN = c(" 95 or more " = 95, " Don t know " = 98),
Q502BU = c(" Days " = 1, " Months " = 2, " Years " = 3, " Special answers " = 9),
Q502C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q502D = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q502E = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q503A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q503BN = c(" 95 or more " = 95, " Don t know " = 98),
Q503BU = c(" Days " = 1, " Months " = 2, " Years " = 3, " Special answers " = 9),
Q503C = c(" Continuous " = 1, " On and off " = 2, " Don t know " = 8),
Q504A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q504B = c(" 95 or more " = 95, " Don t know " = 98),
Q505A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q505B = c(" 95 or more " = 95, " Don t know " = 98),
Q505C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q505D = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q506 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q507A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q507B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q507C = c(" 95 or more " = 95, " Don t know " = 98),
Q507DN = c(" 95 or more " = 95, " Don t know " = 98),
Q507DU = c(" Minutes " = 1, " Hours " = 2, " Special answers " = 9),
Q508A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q508B = c(" 95 or more " = 95, " Don t know " = 98),
Q508C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q508D = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q509A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q509B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q509C = c(" 95 or more " = 95, " Don t know " = 98),
Q509D = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q509E = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q510 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q511A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q511B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q511CN = c(" 95 or more " = 95, " Don t know " = 98),
Q511CU = c(" Hours " = 1, " Days " = 2, " Weeks " = 3, " Months " = 4, " Special answers " = 9),
Q511D = c(" Upper abdomen " = 1, " Lower abdomen " = 2, " Upper and lower abdomen " = 3, " Don t know " = 8),
Q512A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q512BN = c(" 95 or more " = 95, " Don t know " = 98),
Q512BU = c(" Days " = 1, " Months " = 2, " Special answers " = 9),
Q512C = c(" Rapidly " = 1, " Slowly " = 2, " Don t know " = 8),
Q513A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q513BN = c(" 95 or more " = 95, " Don t know " = 98),
Q513BU = c(" Days " = 1, " Months " = 2, " Special answers " = 9),
Q514 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q515A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q515B = c(" 95 or more " = 95, " Don t know " = 98),
Q516A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q516B = c(" 95 or more " = 95, " Don t know " = 98),
Q517A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q517BN = c(" 95 or more " = 95, " Don t know " = 98),
Q517BU = c(" Months " = 1, " Years " = 2, " Special answers " = 9),
Q518A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q518B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q518C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q518D = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q519A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q519B = c(" 95 or more " = 95, " Don t know " = 98),
Q519C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q520A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q520B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q520C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q520D = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q522A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q522B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q523A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q523B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q523C = c(" 95 or more " = 95, " Don t know " = 98),
Q524A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q524B = c(" 95 or more " = 95, " Don t know " = 98),
Q525 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q526 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q527A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q527B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q528 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q529 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q530 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q531 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q532A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q532B = c(" 95 or more " = 95, " Don t know " = 98),
Q533A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q533B = c(" 95 or more " = 95, " Don t know " = 98),
Q533C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q534 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q535A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q535B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q535C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q535D = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q535E = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q536A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q536B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q536C = c(" Right side of body " = 1, " Left side of body " = 2, " Lower part of body " = 3, " Upper part of body " = 4, " One leg only " = 5, " One arm only " = 6, " Whole body " = 7, " Other " = 8, " Don t know " = 98),
Q537A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q537B = c(" 95 or more " = 95, " Don t know " = 98),
Q537C = c(" Solids " = 1, " Liquids " = 2, " Both " = 3, " Don t know " = 8),
Q538 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q539A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q539B = c(" 95 or more " = 95, " Don t know " = 98),
Q540 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q541 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q542 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q601 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q602 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q603A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q603B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q603C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q603E = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q603F = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q603G = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q603I = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q603J = c(" 95 or more " = 95, " Don t know " = 98),
Q604 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q605 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q606 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q608 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q608A = c(" Yes, no pregnancy in 12 months before death " = 1, " No " = 2, " Don t know " = 8),
Q609 = c(" Don t know " = 98),
Q611 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q612A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q612B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q613 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q614 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q615 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q616B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q617A = c(" Don t know " = 98),
Q617C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q618 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q619 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q620 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q621 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q622B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q622C = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q622D = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q623A = c(" Yes " = 1, " No " = 2, " NA-Labour never started " = 3, " Don t know " = 8),
Q623B = c(" Before labour started " = 1, " During labour " = 2, " NA-Water never broke " = 3, " Don t know " = 8),
Q623C = c(" Less than 24 hours " = 1, " More than 24 hours " = 2, " NA-Baby never delivered " = 3, " Don t know " = 8),
Q623D = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q624 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q625 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q626 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q627 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q628 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q630 = c(" Govt hospital " = 11, " Govt health center/clinic " = 12, " Govt health post/chps " = 13, " Mobile clinic/outreach " = 14, " Other public sector " = 16, " Private hospital/clinic " = 21, " Fp/ppag clinic " = 22, " Mobile clinic/outreach " = 23, " Maternity home " = 24, " Other private medical sector " = 26, " Deceased woman s home " = 31, " Other home " = 32, " TBA s home " = 33, " Other " = 96),
Q631 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q633 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q634 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q635 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q636 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q637 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q638 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q639 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q640 = c(" 95 or more " = 95, " Never in labour " = 96, " Don t know " = 98),
Q701 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q702A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q702C = c(" 80 or more " = 80, " Don t know " = 98),
Q801 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q802 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q803 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q804 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q805 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q806 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q807 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q808A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q808B = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q809 = c(" Yes " = 1, " No " = 2, " Never admitted " = 3, " Never discharged " = 4, " Don t know " = 8),
Q810A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q810C = c(" Name or address of health facility " = 6),
Q811A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q811B = c(" Health worker said " = 6),
Q812A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q812B = c(" Yes " = 1, " No " = 2),
Q813AD = c(" Day not recorded " = 98),
Q813AM = c(" January " = 1, " February " = 2, " March " = 3, " April " = 4, " May " = 5, " June " = 6, " July " = 7, " August " = 8, " September " = 9, " October " = 10, " November " = 11, " December " = 12, " Month not recorded " = 98),
Q813AY = c(" Year not recorded " = 9998),
Q814AD = c(" No second last visit " = 96, " Day not recorded " = 98),
Q814AM = c(" January " = 1, " February " = 2, " March " = 3, " April " = 4, " May " = 5, " June " = 6, " July " = 7, " August " = 8, " September " = 9, " October " = 10, " November " = 11, " December " = 12, " Month not recorded " = 98),
Q814AY = c(" Year not recorded " = 9998),
Q815AD = c(" No note " = 96, " Day not recorded " = 98),
Q815AM = c(" January " = 1, " February " = 2, " March " = 3, " April " = 4, " May " = 5, " June " = 6, " July " = 7, " August " = 8, " September " = 9, " October " = 10, " November " = 11, " December " = 12, " Month not recorded " = 98),
Q815AY = c(" Year not recorded " = 9998),
Q815B = c(" Last note on health records " = 6),
Q901A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q901B = c(" Name " = 1, " Don t know " = 8),
Q902A = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q902B = c(" Shared taxi " = 11, " Individual taxi " = 12, " Trotro " = 13, " Bus (metro mass) " = 14, " Private car " = 15, " Train " = 16, " Motorcycle " = 17, " Canoe/boat/ferry with motor " = 18, " Ambulance " = 19, " Canoe/boat/ferry, no motor " = 20, " Bicycle " = 21, " On foot " = 22, " Other " = 96, " Don t know " = 98),
Q902C = c(" 995 or more minutes " = 995, " Don t know " = 998),
Q903 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q904 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q905 = c(" Yes " = 1, " No " = 2, " NA-Dead on arrival " = 3, " Don t know " = 8),
Q906 = c(" 995 or more minutes " = 995, " Don t know " = 998),
Q907 = c(" Yes, there were doubts " = 1, " No doubts-illness not serious " = 2, " No doubts-death inevitable " = 3, " No doubts-went to facility " = 4, " No doubts-not sick before death " = 5, " Don t know " = 8),
Q908 = c(" Yes, traditional/herbal only " = 1, " Yes, spiritual only " = 2, " Yes, both " = 3, " No " = 4, " Don t know " = 8),
Q909 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
Q910 = c(" Yes " = 1, " No " = 2, " Don t know " = 8),
QCONSENT = c(" Respondent agrees to be interviewed " = 1, " Respondent does not agree to be interviewed " = 2),
QELIG = c(" Eligible for VA " = 1, " Not eligible based on date of death " = 2, " Not eligible based on age of death " = 3),
QINTM = c(" January " = 1, " February " = 2, " March " = 3, " April " = 4, " May " = 5, " June " = 6, " July " = 7, " August " = 8, " September " = 9, " October " = 10, " November " = 11, " December " = 12),
QLANGI = c(" English " = 0, " Akan " = 1, " Ga " = 2, " Ewe " = 3, " Guan " = 4, " Mole-dagbani " = 5, " Grusi " = 6, " Gurma " = 7, " Mande " = 8, " Other " = 96),
QLANGQ = c(" English " = 0, " Akan " = 1, " Ga " = 2, " Ewe " = 3),
QLANGR = c(" English " = 0, " Akan " = 1, " Ga " = 2, " Ewe " = 3, " Guan " = 4, " Mole-dagbani " = 5, " Grusi " = 6, " Gurma " = 7, " Mande " = 8, " Other " = 96),
QREGION = c(" Western " = 1, " Central " = 2, " Greater Accra " = 3, " Volta " = 4, " Eastern " = 5, " Ashanti " = 6, " Brong Ahafo " = 7, " Northern " = 8, " Upper East " = 9, " Upper West " = 10),
QRESULT = c(" Completed " = 1, " No household member at home or no competent respondent " = 2, " Entire household absent for extended period of time " = 3, " Postponed " = 4, " Refused " = 5, " Dwelling vacant or address not a dwelling " = 6, " Dwelling destroyed " = 7, " Dwelling not found " = 8, " Other " = 9),
QTRANS = c(" Yes " = 1, " No " = 2),
QTYPE = c(" Urban " = 1, " Rural " = 2))
