DATA LIST FILE='C:\COUNTRIES\GH7I\GHCH7IFL.DAT' RECORDS=1
  /
  QHCLUST     1-4   
  QHNUMBER    5-8   
  QLINE       9-10  
  Q212       11-12  
  QREGION    13-14  
  QDISTR     15-18  
  QINTD      19-20  
  QINTM      21-22  
  QINTY      23-26  
  QINTNUM    27-30  
  QRESULT    31-31  
  QVISITS    32-32  
  QSUPERV    33-36  
  QLANGQ     37-38  
  QLANGI     39-40  
  QLANGR     41-42  
  QTRANS     43-43  
  QINTC      44-47  
  QINTCD     48-52  
  QWEIGHT    53-60  
  QTYPE      61-61  
  QCONSENT   62-62  
  Q212B      63-63  
  Q212C      64-64  
  Q212D      65-65  
  Q213       66-66  
  Q215D      67-68  
  Q215M      69-70  
  Q215Y      71-74  
  Q216       75-75  
  Q217       76-77  
  Q220U      78-78  
  Q220N      79-80  
  Q220AAD    81-82  
  Q220AAM    83-84  
  Q220AAY    85-88  
  Q220ABD    89-90  
  Q220ABM    91-92  
  Q220ABY    93-96  
  Q220AC     97-98  
  Q220AD     99-99  
  Q221      100-100 
  QLAST5    101-101 
  Q215C     102-105 
  Q215CD    106-110 
  Q215DI    111-112 
  Q215F     113-113 
  Q220C     114-116 
  Q220F     117-117 
  PREGOUT   118-118 
  Q403      119-120 
  Q405      121-121 
  Q406      122-137  (A)
  Q407      138-144  (A)
  Q408      145-157  (A)
  Q409      158-159 
  Q410      160-160 
  Q411      161-173  (A)
  Q412      174-175 
  Q413A     176-176 
  Q413B     177-177 
  Q413C     178-178 
  Q413D     179-179 
  Q413E     180-180 
  Q413F     181-181 
  Q414      182-182 
  Q415      183-183 
  Q417      184-184 
  Q418      185-185 
  Q419      186-187 
  Q420      188-188 
  Q421      189-191 
  Q422      192-192 
  Q423      193-193 
  Q424      194-195 
  Q425      196-196 
  Q426B     197-197 
  Q427      198-198 
  Q428U     199-199 
  Q428N     200-204  (3)
  Q429      205-212  (A)
  Q430      213-214 
  Q431A     215-230  (A)
  Q431BA    231-231 
  Q431BB    232-232 
  Q431BC    233-233 
  Q431C     234-234 
  Q431D     235-250  (A)
  Q431E     251-251 
  Q431F     252-268  (A)
  Q431G     269-276  (A)
  Q431H     277-278 
  Q431I     279-279 
  Q431J     280-280 
  Q431K     281-282 
  Q431L     283-283 
  Q431M     284-300  (A)
  Q432U     301-301 
  Q432N     302-303 
  Q433A     304-304 
  Q433B     305-305 
  Q434      306-306 
  Q434A     307-307 
  Q435      308-308 
  Q436U     309-309 
  Q436N     310-311 
  Q437      312-313 
  Q438B     314-314 
  Q439U     315-315 
  Q439N     316-317 
  Q440      318-319 
  Q441      320-320 
  Q442U     321-321 
  Q442N     322-323 
  Q443      324-325 
  Q444      326-327 
  Q445B     328-328 
  Q446U     329-329 
  Q446N     330-331 
  Q447      332-333 
  Q448      334-335 
  Q449      336-336 
  Q450U     337-337 
  Q450N     338-339 
  Q451      340-341 
  Q452      342-343 
  Q453B     344-344 
  Q454U     345-345 
  Q454N     346-347 
  Q455      348-349 
  Q456      350-351 
  Q457A     352-352 
  Q457B     353-353 
  Q457C     354-354 
  Q457D     355-355 
  Q457E     356-356 
  Q500      357-358 
  Q501      359-362 
  Q502A     363-364 
  Q502B     365-365 
  Q502C     366-387  (A)
  Q503      388-388 
  Q504      389-389 
  Q505U     390-390 
  Q505N     391-392 
  Q506      393-394 
  Q507      395-396 
  Q508      397-398 
  Q509A     399-399 
  Q509B     400-406  (A)
  Q510      407-407 
  Q511      408-408 
  Q512      409-409 
  Q513      410-410 
  Q514      411-411 
  Q515      412-412 
  Q516      413-413 
  Q517      414-414 
  Q518      415-415 
  Q519      416-416 
  Q520      417-417 
  Q521      418-421 
  Q522      422-422 
  Q523      423-423 
  Q524      424-427 
  Q525      428-428 
  Q526      429-429 
  Q527      430-433 
  Q528      434-434 
  Q529      435-435 
  Q530      436-439 
  Q531      440-440 
  Q532      441-441 
  Q533      442-443 
  Q534      444-445 
  Q535      446-447 
  Q536A     448-448 
  Q536B     449-455  (A)
  Q537      456-456 
  Q538      457-457 
  Q539B     458-458 
  Q540      459-459 
  Q541      460-460 
  Q542      461-461 
  Q543      462-462 
  Q544      463-463 
  Q545      464-464 
  Q546      465-465 
  Q547      466-466 
  Q548      467-467 
  Q549      468-468 
  Q550      469-469 
  Q551      470-470 
  Q552      471-474 
  Q553      475-475 
  Q554      476-476 
  Q555      477-480 
  Q556      481-481 
  Q557      482-482 
  Q558      483-486 
  Q559      487-487 
  Q560      488-488 
  Q561      489-492 
  Q562      493-493 
  Q563B     494-494 
  Q564      495-498  (A)
  Q565      499-513  (A)
  Q566A     514-514 
  Q566BU    515-515 
  Q566BN    516-517 
  Q567      518-518 
  Q568      519-519 
  Q569      520-526  (A)
  Q570      527-527 
  Q571      528-529 
  Q572      530-530 
  Q573      531-531 
  Q574      532-532 
  Q575      533-533 
  Q600      534-535 
  Q601      536-539 
  Q602      540-540 
  Q603      541-542 
  Q604A     543-543 
  Q604B     544-552  (A)
  Q604C     553-567  (A)
  Q605      568-568 
  Q606      569-570 
  Q607      571-571 
  Q608      572-572 
  Q609B     573-573 
  Q610      574-574 
  Q611      575-575 
  Q612      576-576 
  Q613      577-577 
  Q614      578-578 
  Q615      579-579 
  Q616      580-580 
  Q617      581-581 
  Q618      582-582 
  Q619      583-583 
  Q620      584-584 
  Q621      585-585 
  Q622      586-589 
  Q623      590-590 
  Q624      591-591 
  Q625      592-595 
  Q626      596-596 
  Q627      597-597 
  Q628      598-601 
  Q629      602-602 
  Q630      603-603 
  Q631      604-607 
  Q632      608-608 
  Q633      609-609 
  Q634      610-613  (A)
  Q635      614-628  (A)
  Q636A     629-629 
  Q636BU    630-630 
  Q636BN    631-632 
  Q637      633-633 
  Q638      634-634 
  Q639      635-641  (A)
  Q640      642-642 
  Q641      643-644 
  Q642      645-645 
  Q643      646-646 
  Q644      647-647 
  Q645      648-648 
 .
VARIABLE LABELS
   QHCLUST  "Cluster number"
  /QHNUMBER "Household number"
  /QLINE    "Individual line number"
  /Q212     "Line number of child"
  /QREGION  "Region"
  /QDISTR   "District"
  /QINTD    "Day of interview"
  /QINTM    "Month of interview"
  /QINTY    "Year of interview"
  /QINTNUM  "Interviewer number"
  /QRESULT  "Result of individual interview"
  /QVISITS  "Total number of visits"
  /QSUPERV  "Supervisor number"
  /QLANGQ   "Language of questionnaire"
  /QLANGI   "Language of interview"
  /QLANGR   "Language of respondent"
  /QTRANS   "Translator used"
  /QINTC    "Date of interview (CMC)"
  /QINTCD   "Date of interview Century Day Code (CDC)"
  /QWEIGHT  "Sample weight (6 decimals)"
  /QTYPE    "Type of place of residence"
  /QCONSENT "Consent agreement"
  /Q212B    "Single or Multiple Birth"
  /Q212C    "Born alive/dead or miscarriage/abortion"
  /Q212D    "Did baby cry, move or breathe"
  /Q213     "Sex of child"
  /Q215D    "Day of birth"
  /Q215M    "Month of birth"
  /Q215Y    "Year of birth"
  /Q216     "Child is still alive"
  /Q217     "Current age of child"
  /Q220U    "Age at death (units)"
  /Q220N    "Age at death (number)"
  /Q220AAD  "Day of dead"
  /Q220AAM  "Month of dead"
  /Q220AAY  "Year of dead"
  /Q220ABD  "Day of pregnancy termination"
  /Q220ABM  "Month of pregnancy termination"
  /Q220ABY  "Year of pregnancy termination"
  /Q220AC   "Pregnancy duration"
  /Q220AD   "Do something to end the pregnancy"
  /Q221     "Live birth between births"
  /QLAST5   "Child born alive/dead in the last 5 years"
  /Q215C    "Date of birth of child (CMC)"
  /Q215CD   "Date of birth of child Century Day Code (CDC)"
  /Q215DI   "Imputed day of birth"
  /Q215F    "Date flag for Q215C"
  /Q220C    "Age at death months (imputed)"
  /Q220F    "Date flag for Q220C"
  /PREGOUT  "Pregnancy outcome"
  /Q403     "Line number"
  /Q405     "Received antenatal care for pregnancy"
  /Q406     "Reason not seeing anyone for antenatal care"
  /Q407     "Provider of antenatal care for pregnancy"
  /Q408     "Where antenatal care took place"
  /Q409     "Months pregnant at first antenatal care"
  /Q410     "First antenatal care because of problems or checkup"
  /Q411     "Problems during first antenatal care"
  /Q412     "Antenatal visits during pregnancy"
  /Q413A    "Antenatal care: Blood pressure"
  /Q413B    "Antenatal care: Urine sample"
  /Q413C    "Antenatal care: Blood sample"
  /Q413D    "Antenatal care: Weight"
  /Q413E    "During any antenatal care told about pregnancy complications"
  /Q413F    "Told about where to go if had any complications"
  /Q414     "Tetanus injection during pregnancy"
  /Q415     "Number of tetanus injections"
  /Q417     "Tetanus injections before pregnancy"
  /Q418     "Number of tetanus injections before pregnancy"
  /Q419     "Years ago received last tetanus injection before pregnancy"
  /Q420     "Iron tablets during pregnancy"
  /Q421     "Number of days took iron tablets"
  /Q422     "Drugs for intestinal parasites"
  /Q423     "During pregnancy took SP/Fansidar for malaria"
  /Q424     "How many times took SP/Fansidar (Malaria)"
  /Q425     "Took SP/Fansidar during antenatal visit (Malaria)"
  /Q426B    "Size of child at birth"
  /Q427     "Weighed at birth"
  /Q428U    "Weight at birth (units)"
  /Q428N    "Weight in Kilograms"
  /Q429     "Assistance at delivery"
  /Q430     "Place of delivery"
  /Q431A    "Reason not delivering at hospital/health centre"
  /Q431BA   "Procedure at delivery: Forceps or vacuum"
  /Q431BB   "Procedure at delivery: Blood transfusion"
  /Q431BC   "Procedure at delivery: Intravenous fluid"
  /Q431C    "Suffered from any problem before/after delivery"
  /Q431D    "Problems suffered before/after delivery"
  /Q431E    "Saw anyone about the problem"
  /Q431F    "Reason not seeing anyone about the problem"
  /Q431G    "Who saw the problem"
  /Q431H    "Where was treated for the problem"
  /Q431I    "Condition improved after treated"
  /Q431J    "Referred/told to go to another place"
  /Q431K    "Where was referred/told to go for treatment"
  /Q431L    "Went to the referred place"
  /Q431M    "Reason not going to the referred place for treatment"
  /Q432U    "Time spent in health facility after delivery (Units)"
  /Q432N    "Time spent in health facility after delivery (Number)"
  /Q433A    "Delivery by caesarean section"
  /Q433B    "Timing of decision on caesarean section"
  /Q434     "Child was put on the chest immediately after birth"
  /Q434A    "Child bare skin touched respondent bare skin"
  /Q435     "Postnatal check on respondent before discharge"
  /Q436U    "First postnatal check on respondent (Units)"
  /Q436N    "First postnatal check on respondent (Number)"
  /Q437     "Person giving postnatal care to respondent"
  /Q438B    "First postnatal check on child in facility"
  /Q439U    "Time first postnatal check on child in facility (unit)"
  /Q439N    "Time first postnatal check on child in facility (number)"
  /Q440     "Person giving postnatal care to child  in facility"
  /Q441     "Checkup on respondent after discharge from place of delivery"
  /Q442U    "Time checkup on respondent after discharge (unit)"
  /Q442N    "Time checkup on respondent after discharge (number)"
  /Q443     "Person giving checkup on respondent after discharge"
  /Q444     "Place of checkup on respondent after discharge"
  /Q445B    "Health child checked in first 2 months after birth"
  /Q446U    "First postnatal check on child (unit)"
  /Q446N    "First postnatal check on child (number)"
  /Q447     "Person giving postnatal check on child"
  /Q448     "Place of first postnatal check"
  /Q449     "Respondent received postnatal check after home delivery"
  /Q450U    "Time respondent received postnatal check after home delivery (units)"
  /Q450N    "Time respondent received postnatal check after home delivery (number)"
  /Q451     "Person giving postnatal check on respondent after home delivery"
  /Q452     "Place postnatal check on respondent after home delivery"
  /Q453B    "Child received postnatal check after home delivery"
  /Q454U    "Time child received postnatal check after home delivery (units)"
  /Q454N    "Time child received postnatal check after home delivery (number)"
  /Q455     "Person giving postnatal check on child after home delivery"
  /Q456     "Place postnatal check on child after home delivery"
  /Q457A    "During first two days, health care provider: examine the cord"
  /Q457B    "During first two days, health care provider: measure temperature"
  /Q457C    "During first two days, health care provider: counsel on danger signs for newborns"
  /Q457D    "During first two days, health care provider: counsel on breastfeeding"
  /Q457E    "During first two days, health care provider: observe breastfeeding"
  /Q500     "Line number of recent abortion in 2012 or later"
  /Q501     "Year of most recent abortion in 2012 or after"
  /Q502A    "Main reason for abortion"
  /Q502B    "Any other reason for abortion"
  /Q502C    "Other reasons for abortion"
  /Q503     "Partner's attitude toward abortion"
  /Q504     "Multiple steps to end pregnancy"
  /Q505U    "Time between first attempt and final (Units)"
  /Q505N    "Time between first attempt and final (Number)"
  /Q506     "First action to end pregnancy"
  /Q507     "Provider for first step to end pregnancy"
  /Q508     "Source for first step to end pregnancy"
  /Q509A    "Anything paid to get procedure done"
  /Q509B    "Person who paid for first step to end pregnancy"
  /Q510     "Bleeding from first step to end pregnancy"
  /Q511     "Bleeding was mild/moderate/severe"
  /Q512     "Pain from first step to end pregnancy"
  /Q513     "Pain was mild/moderate/severe"
  /Q514     "Fever from first step to end pregnancy"
  /Q515     "Fever was mild/moderate/severe"
  /Q516     "Injury or perforation from first step to end pregnancy"
  /Q517     "Injury or perforation was mild/moderate/severe"
  /Q518     "Vaginal discharge from first step to end pregnancy"
  /Q519     "Vaginal discharge was mild/moderate/severe"
  /Q520     "Any other problem (1) from first step to end pregnancy"
  /Q521     "Problem (1) from first step to end pregnancy"
  /Q522     "Problem (1) mild/moderate/severe from first step to end pregnancy"
  /Q523     "Any other problem (2) from first step to end pregnancy"
  /Q524     "Problem (2) from first step to end pregnancy"
  /Q525     "Problem (2) mild/moderate/severe from first step to end pregnancy"
  /Q526     "Any other problem (3) from first step to end pregnancy"
  /Q527     "Problem (3) from first step to end pregnancy"
  /Q528     "Problem (3) mild/moderate/severe from first step to end pregnancy"
  /Q529     "Any other problem (4) from first step to end pregnancy"
  /Q530     "Problem (4) from first step to end pregnancy"
  /Q531     "Problem (4) mild/moderate/severe from first step to end pregnancy"
  /Q532     "Took any pain relievers after first step to end pregnancy"
  /Q533     "Last action to end pregnancy"
  /Q534     "Provider for last step to end pregnancy"
  /Q535     "Source for last step to end pregnancy"
  /Q536A    "Anything paid to get procedure done"
  /Q536B    "Person who paid for last step to end pregnancy"
  /Q537     "Took antibiotics after abortion"
  /Q538     "Took any pain relievers after last step to end pregnancy"
  /Q539B    "Local anesthesia for abortion"
  /Q540     "Health problems in first month after abortion"
  /Q541     "Bleeding in first month after abortion"
  /Q542     "Bleeding was mild/moderate/severe"
  /Q543     "Pain in first month after abortion"
  /Q544     "Pain was mild/moderate/severe"
  /Q545     "Fever in first month after abortion"
  /Q546     "Fever was mild/moderate/severe"
  /Q547     "Injury or perforation in first month after abortion"
  /Q548     "Injury or perforation was mild/moderate/severe"
  /Q549     "Foul-smelling discharge in first month after abortion"
  /Q550     "Foul-smelling discharge was mild/moderate/severe"
  /Q551     "Any other problem (1) in first month after abortion"
  /Q552     "Problem (1) in first month after abortion"
  /Q553     "Problem (1) mild/moderate/severe in first month after abortion"
  /Q554     "Any other problem (2) in first month after abortion"
  /Q555     "Problem (2) in first month after abortion"
  /Q556     "Problem (2) mild/moderate/severe in first month after abortion"
  /Q557     "Any other problem (3) in first month after abortion"
  /Q558     "Problem (3) in first month after abortion"
  /Q559     "Problem (3) mild/moderate/severe in first month after abortion"
  /Q560     "Any other problem (4) in first month after abortion"
  /Q561     "Problem (4) in first month after abortion"
  /Q562     "Problem (4) mild/moderate/severe in first month after abortion"
  /Q563B    "Received treatment for health problems due to abortion"
  /Q564     "Type of treatment received for health problems due to abortion"
  /Q565     "Source of treatment for health problems due to abortion"
  /Q566A    "Spent any nights in a health facility in the first month after abortion"
  /Q566BU   "Time spent in health facility due to abortion (Units)"
  /Q566BN   "Time spent in health facility due to abortion (Number)"
  /Q567     "Visited by doctor or health worker before or after abortion"
  /Q568     "Any health problems six months after abortion"
  /Q569     "Health problems six months after abortion"
  /Q570     "Using contraception at the time she became pregnant"
  /Q571     "Contraception used at the time she became pregnant"
  /Q572     "Health professional spoke about contraception before or after abortion"
  /Q573     "When health professional spoke about contraception"
  /Q574     "Health worker gave contraception method or FP advice after abortion"
  /Q575     "Given method of contraception, prescription or referral after abortion"
  /Q600     "Line number of recent miscarriage in 2012 or later"
  /Q601     "Year of most recent miscarriage in 2012 or after"
  /Q602     "Cause of miscarriage"
  /Q603     "Where miscarriage occurred"
  /Q604A    "Sought help for miscarriage"
  /Q604B    "From whom sought help for miscarriage"
  /Q604C    "Place got help for miscarriage"
  /Q605     "Uterus cleaned after miscarriage"
  /Q606     "Method to clean uterus"
  /Q607     "Took antibiotics after miscarriage"
  /Q608     "Given pain relievers after miscarriage"
  /Q609B    "Anesthesia for miscarriage"
  /Q610     "Any health problems due to miscarriage"
  /Q611     "Bleeding from miscarriage"
  /Q612     "Bleeding was mild/moderate/severe"
  /Q613     "Pain from miscarriage"
  /Q614     "Pain was mild/moderate/severe"
  /Q615     "Fever from miscarriage"
  /Q616     "Fever was mild/moderate/severe"
  /Q617     "Injury or perforation from miscarriage"
  /Q618     "Injury or perforation was mild/moderate/severe"
  /Q619     "Foul-smelling discharge from miscarriage"
  /Q620     "Foul-smelling discharge was mild/moderate/severe"
  /Q621     "Any other problem (1) from miscarriage"
  /Q622     "Problem (1) from miscarriage"
  /Q623     "Problem (1) mild/moderate/severe from miscarriage"
  /Q624     "Any other problem (2) from miscarriage"
  /Q625     "Problem (2) from miscarriage"
  /Q626     "Problem (2) mild/moderate/severe from miscarriage"
  /Q627     "Any other problem (3) from miscarriage"
  /Q628     "Problem (3) from miscarriage"
  /Q629     "Problem (3) mild/moderate/severe from miscarriage"
  /Q630     "Any other problem (4) from miscarriage"
  /Q631     "Problem (4) from miscarriage"
  /Q632     "Problem (4) mild/moderate/severe from miscarriage"
  /Q633     "Received treatment for health problems due to miscarriage"
  /Q634     "Type of treatment received for health problems due to miscarriage"
  /Q635     "Source of treatment for health problems due to miscarriage"
  /Q636A    "Spent any nights in a health facility in the first month after miscarriage"
  /Q636BU   "Time spent in health facility due to miscarriage (Units)"
  /Q636BN   "Time spent in health facility due to miscarriage (Number)"
  /Q637     "Visited by doctor or health worker before or after miscarriage"
  /Q638     "Any health problems six months after miscarriage"
  /Q639     "Health problems six months after miscarriage"
  /Q640     "Using contraception at the time she became pregnant"
  /Q641     "Contraception used at the time she became pregnant"
  /Q642     "Health professional spoke about contraception before or after miscarriage"
  /Q643     "When health professional spoke about contraception"
  /Q644     "Health worker gave contraception method or FP advice after miscarriage"
  /Q645     "Given method of contraception, prescription or referral after miscarriage"
 .
MISSING VALUE
   Q431BA   (9)
  /Q431BB   (9)
  /Q431BC   (9)
  /Q432N    (99)
  /Q433A    (9)
  /Q433B    (9)
  /Q435     (9)
  /Q438B    (9)
  /Q441     (9)
  /Q445B    (9)
  /Q539B    (9)
 .
VALUE LABELS
   QREGION 
      1 "Western"
      2 "Central"
      3 "Greater accra"
      4 "Volta"
      5 "Eastern"
      6 "Ashanti"
      7 "Brong ahafo"
      8 "Northern"
      9 "Upper east"
     10 "Upper west"
  /QINTM   
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
  /QRESULT 
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
  /QLANGQ  
      0 "English"
      1 "Akan"
      2 "Ga"
      3 "Ewe"
  /QLANGI  
      0 "English"
      1 "Akan"
      2 "Ga"
      3 "Ewe"
      4 "Guan"
      5 "Mole-dagbani"
      6 "Grusi"
      7 "Gurma"
      8 "Mande"
     96 "Other"
  /QLANGR  
      0 "English"
      1 "Akan"
      2 "Ga"
      3 "Ewe"
      4 "Guan"
      5 "Mole-dagbani"
      6 "Grusi"
      7 "Gurma"
      8 "Mande"
     96 "Other"
  /QTRANS  
      1 "Yes"
      2 "No"
  /QTYPE   
      1 "Urban"
      2 "Rural"
  /QCONSENT
      1 "Respondent agrees to be interviewed"
      2 "Respondent does not agree to be interviewed"
  /Q212B   
      1 "Single"
      2 "Multiple"
  /Q212C   
      1 "Born alive"
      2 "Born dead"
      3 "Miscarriage"
      4 "Abortion"
  /Q212D   
      1 "Yes"
      2 "No"
  /Q213    
      1 "Boy"
      2 "Girl"
  /Q215D   
     98 "Don't know day"
  /Q215M   
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     97 "Inconsistent"
     98 "Don't know month"
  /Q215Y   
   9997 "Inconsistent"
   9998 "Don't know year"
  /Q216    
      1 "Yes"
      2 "No"
  /Q217    
     97 "Inconsistent"
     98 "Don't know age"
  /Q220U   
      1 "Days"
      2 "Months"
      3 "Years"
      9 "Special answers"
  /Q220AAD 
     98 "Don't know day"
  /Q220AAM 
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Don't know month"
  /Q220AAY 
   9998 "Don't know year"
  /Q220ABD 
     98 "Don't know day"
  /Q220ABM 
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     97 "Inconsistent"
     98 "Don't know month"
  /Q220ABY 
   9997 "Inconsistent"
   9998 "Don't know year"
  /Q220AD  
      1 "Yes"
      2 "No"
  /Q221    
      1 "Yes"
      2 "No"
  /QLAST5  
      0 "No"
      1 "Yes"
  /Q215F   
      0 "Month, year and day"
      1 "Month and year"
      2 "Month and age -y imp"
      3 "Year and age - m imp"
      4 "Y & age - y ignored"
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
  /Q220F   
      0 "No flag"
      1 "> interview"
      2 "< breastfeeding"
      3 "< age supplemented"
      4 "< first breastfed"
      5 "< last vaccination"
      6 "Outside range"
      7 "Imputed, units given"
      8 "Imputed, no units"
  /PREGOUT 
      1 "Live birth"
      2 "Stillbirth"
      3 "Miscarriage"
      4 "Abortion"
  /Q405    
      1 "Yes"
      2 "No"
  /Q406    
   'A               ' "Not necessary"
   'B               ' "Not customary"
   'C               ' "Lack of money"
   'D               ' "Too far"
   'E               ' "Transportation problem"
   'F               ' "No one to accompany"
   'G               ' "Good service not available"
   'H               ' "Not permitted by family"
   'I               ' "Better service at home"
   'J               ' "Did not know where to go"
   'K               ' "No female doctor available"
   'L               ' "Inconvenient service hour"
   'M               ' "Afraid to go"
   'N               ' "Long waiting time"
   'O               ' "Religious reason"
   'X               ' "Other"
  /Q407    
   'A      ' "Health personnel: Doctor"
   'B      ' "Health personnel: Nurse/midwife"
   'C      ' "Health personnel: Com  health officer/nurse"
   'D      ' "Other person: Traditional birth attendant"
   'E      ' "Other person: Village health volunteer"
   'F      ' "Other person: Traditional health practitioner"
   'X      ' "Other"
  /Q408    
   'A            ' "Her home"
   'B            ' "Other home"
   'C            ' "Public: Govt hospital"
   'D            ' "Public: Govt health center/clinic"
   'E            ' "Public: Govt health post/chps"
   'F            ' "Public: Mobile clinic/outreach"
   'G            ' "Public: Other public sector"
   'H            ' "Private: Hospital/clinic"
   'I            ' "Private: Fp/ppag clinic"
   'J            ' "Private: Mobile clinic/outreach"
   'K            ' "Private: Maternity home"
   'L            ' "Private: Other private med sector"
   'X            ' "Other"
  /Q409    
     98 "Don't know"
  /Q410    
      1 "Problem"
      2 "Just checkup"
  /Q411    
   'A            ' "Headache"
   'B            ' "Blurry vision"
   'C            ' "Edema/pre-eclampsia"
   'D            ' "Vaginal bleeding"
   'E            ' "Convulsions/eclampsia"
   'F            ' "Tetanus"
   'G            ' "Foul-smelling discharge"
   'H            ' "Lower abdominal pain"
   'I            ' "Fell down"
   'J            ' "Baby movement was low"
   'K            ' "Varicose vein"
   'L            ' "Excessive vomiting"
   'M            ' "Anaemia/body pains/fever/body weakness/malaria"
   'X            ' "Other"
  /Q412    
     98 "Don't know"
  /Q413A   
      1 "Yes"
      2 "No"
  /Q413B   
      1 "Yes"
      2 "No"
  /Q413C   
      1 "Yes"
      2 "No"
  /Q413D   
      1 "Yes"
      2 "No"
  /Q413E   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q413F   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q414    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q415    
      7 "7 or more"
      8 "Don't know"
  /Q417    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q418    
      7 "7 or more"
      8 "Don't know"
  /Q420    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q421    
      0 "Didn't take any"
    998 "Don't know"
  /Q422    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q423    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q424    
     98 "Don't know"
  /Q425    
      1 "Antenatal visit"
      2 "Another facility visit"
      6 "Other source"
  /Q426B   
      1 "Very large"
      2 "Larger than average"
      3 "Average"
      4 "Smaller than average"
      5 "Very small"
      8 "Don't know"
  /Q427    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q428U   
      1 "Kilograms from card"
      2 "Kilograms from recall"
      9 "Special answers"
  /Q428N   
   9.998 "Don't know"
  /Q429    
   'A       ' "Health personnel: Doctor"
   'B       ' "Health personnel: Nurse/midwife"
   'C       ' "Health personnel: Com  health officer/nurse"
   'D       ' "Other person: Traditional birth attendant"
   'E       ' "Other person: Village health volunteer"
   'F       ' "Other person: Traditional health practitioner"
   'G       ' "Other person: Relative/friend"
   'X       ' "Other"
   'Y       ' "No one assisted"
  /Q430    
     11 "Her home"
     12 "Other home"
     21 "Public: Govt hospital"
     22 "Public: Govt health center/clinic"
     23 "Public: Govt health post/chps"
     24 "Public: Mobile clinic/outreach"
     26 "Public: Other public sector"
     31 "Private: Hospital/clinic"
     32 "Private: Fp/ppag clinic"
     33 "Private: Mobile clinic/outreach"
     34 "Private: Maternity home"
     36 "Private: Other private med sector"
     96 "Other"
  /Q431A   
   'A               ' "Not necessary"
   'B               ' "Not customary"
   'C               ' "Lack of money"
   'D               ' "Too far"
   'E               ' "Transportation problem"
   'F               ' "No one to accompany"
   'G               ' "Good service not available"
   'H               ' "Not permitted by family"
   'I               ' "Better service at home"
   'J               ' "Did not know where to go"
   'K               ' "No female doctor available"
   'L               ' "Inconvenient service hour"
   'M               ' "Afraid to go"
   'N               ' "Long waiting time"
   'O               ' "Religious reason"
   'P               ' "Baby came early than expected time"
   'X               ' "Other"
  /Q431BA  
      1 "Yes"
      2 "No"
  /Q431BB  
      1 "Yes"
      2 "No"
  /Q431BC  
      1 "Yes"
      2 "No"
  /Q431C   
      1 "Yes"
      2 "No"
  /Q431D   
   'A               ' "Headache"
   'B               ' "Blurry vision"
   'C               ' "Edema/pre-eclampsia"
   'D               ' "Excessive bleeding"
   'E               ' "Convulsions/eclampsia"
   'F               ' "Tetanus"
   'G               ' "Foul-smelling discharge"
   'H               ' "Baby movement was low"
   'I               ' "Baby's hands/feet came out first"
   'J               ' "Prolonged labour"
   'K               ' "Obstructed labour"
   'L               ' "Torn uterus"
   'M               ' "Placenta previa/retained"
   'N               ' "High fever"
   'O               ' "Fistula"
   'P               ' "Abdominal pain"
   'X               ' "Other"
  /Q431E   
      1 "Yes"
      2 "No"
  /Q431F   
   'A                ' "Not necessary"
   'B                ' "Not customary"
   'C                ' "Lack of money"
   'D                ' "Too far"
   'E                ' "Transportation problem"
   'F                ' "No one to accompany"
   'G                ' "Good service not available"
   'H                ' "Not permitted by family"
   'I                ' "Better service at home"
   'J                ' "Did not know where to go"
   'K                ' "No female doctor available"
   'L                ' "Inconvenient service hour"
   'M                ' "Afraid to go"
   'N                ' "Long waiting time"
   'O                ' "Religious reason"
   'P                ' "Not life threatening"
   'X                ' "Other"
  /Q431G   
   'A       ' "Health Personnel: Doctor"
   'B       ' "Health Personnel: Nurse/midwife"
   'C       ' "Health Personnel: Com  health officer/nurse"
   'D       ' "Other person: Traditional birth attendant"
   'E       ' "Other person: Village health volunteer"
   'F       ' "Other person: Traditional health practitioner"
   'G       ' "Other person: Relative/friend"
   'X       ' "Other"
  /Q431H   
     11 "Her home"
     12 "Other home"
     21 "Public: Govt hospital"
     22 "Public: Govt health center/clinic"
     23 "Public: Govt health post/chps"
     24 "Public: Mobile clinic/outreach"
     26 "Public: Other public sector"
     31 "Private: Hospital/clinic"
     32 "Private: Fp/ppag clinic"
     33 "Private: Mobile clinic/outreach"
     34 "Private: Maternity home"
     36 "Private: Other private med sector"
     96 "Other"
  /Q431I   
      1 "No change"
      2 "Improved"
      3 "Worsened"
      8 "Don't know"
  /Q431J   
      1 "Yes"
      2 "No"
  /Q431K   
     21 "Public: Govt hospital"
     22 "Public: Govt health center/clinic"
     23 "Public: Govt health post/chps"
     24 "Public: Mobile clinic/outreach"
     26 "Public: Other public sector"
     31 "Private: Hospital/clinic"
     32 "Private: Fp/ppag clinic"
     33 "Private: Mobile clinic/outreach"
     34 "Private: Maternity home"
     36 "Private: Other private med sector"
     96 "Other"
  /Q431L   
      1 "Yes"
      2 "No"
  /Q431M   
   'A                ' "Not necessary"
   'B                ' "Not customary"
   'C                ' "Lack of money"
   'D                ' "Too far"
   'E                ' "Transportation problem"
   'F                ' "No one to accompany"
   'G                ' "Good service not available"
   'H                ' "Not permitted by family"
   'I                ' "Better service at home"
   'J                ' "Did not know where to go"
   'K                ' "No female doctor available"
   'L                ' "Inconvenient service hour"
   'M                ' "Afraid to go"
   'N                ' "Long waiting time"
   'O                ' "Religious reason"
   'P                ' "Not life threatening"
   'X                ' "Other"
  /Q432U   
      1 "Hours"
      2 "Days"
      3 "Weeks"
      9 "Special answers"
  /Q432N   
     98 "Don't know"
  /Q433A   
      1 "Yes"
      2 "No"
  /Q433B   
      1 "Before"
      2 "After"
  /Q434    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q434A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q435    
      1 "Yes"
      2 "No"
  /Q436U   
      1 "Hours"
      2 "Days"
      3 "Weeks"
      9 "Special answers"
  /Q436N   
     98 "Don't know"
  /Q437    
     11 "Health personnel: Doctor"
     12 "Health personnel: Nurse/midwife"
     13 "Health personnel: Com  health officer/nurse"
     21 "Other person: Traditional birth attendant"
     22 "Other person: Village health volunteer"
     23 "Other person: Traditional health practitioner"
     96 "Other"
  /Q438B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q439U   
      1 "Hours"
      2 "Days"
      3 "Weeks"
      9 "Special answers"
  /Q439N   
     98 "Don't know"
  /Q440    
     11 "Health personnel: Doctor"
     12 "Health personnel: Nurse/midwife"
     13 "Health personnel: Com  health officer/nurse"
     21 "Other person: Traditional birth attendant"
     22 "Other person: Village health volunteer"
     23 "Other person: Traditional health practitioner"
     96 "Other"
  /Q441    
      1 "Yes"
      2 "No"
  /Q442U   
      1 "Hours"
      2 "Days"
      3 "Weeks"
      9 "Special answers"
  /Q442N   
     98 "Don't know"
  /Q443    
     11 "Health personnel: Doctor"
     12 "Health personnel: Nurse/midwife"
     13 "Health personnel: Com  health officer/nurse"
     21 "Other person: Traditional birth attendant"
     22 "Other person: Village health volunteer"
     23 "Other person: Traditional health practitioner"
     96 "Other"
  /Q444    
     11 "Her home"
     12 "Other home"
     21 "Public: Govt hospital"
     22 "Public: Govt health center/clinic"
     23 "Public: Govt health post/chps"
     24 "Public: Mobile clinic/outreach"
     26 "Public: Other public sector"
     31 "Private: Hospital/clinic"
     32 "Private: Fp/ppag clinic"
     33 "Private: Mobile clinic/outreach"
     34 "Private: Maternity home"
     36 "Private: Other private med sector"
     96 "Other"
  /Q445B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q446U   
      1 "Hours"
      2 "Days"
      3 "Weeks"
      9 "Special answers"
  /Q446N   
     98 "Don't know"
  /Q447    
     11 "Health personnel: Doctor"
     12 "Health personnel: Nurse/midwife"
     13 "Health personnel: Com  health officer/nurse"
     21 "Other person: Traditional birth attendant"
     22 "Other person: Village health volunteer"
     23 "Other person: Traditional health practitioner"
     96 "Other"
  /Q448    
     11 "Her home"
     12 "Other home"
     21 "Public: Govt hospital"
     22 "Public: Govt health center/clinic"
     23 "Public: Govt health post/chps"
     24 "Public: Mobile clinic/outreach"
     26 "Public: Other public sector"
     31 "Private: Hospital/clinic"
     32 "Private: Fp/ppag clinic"
     33 "Private: Mobile clinic/outreach"
     34 "Private: Maternity home"
     36 "Private: Other private med sector"
     96 "Other"
  /Q449    
      1 "Yes"
      2 "No"
  /Q450U   
      1 "Hours"
      2 "Days"
      3 "Weeks"
      9 "Special answers"
  /Q450N   
     98 "Don't know"
  /Q451    
     11 "Health personnel: Doctor"
     12 "Health personnel: Nurse/midwife"
     13 "Health personnel: Com  health officer/nurse"
     21 "Other person: Traditional birth attendant"
     22 "Other person: Village health volunteer"
     23 "Other person: Traditional health practitioner"
     96 "Other"
  /Q452    
     11 "Her home"
     12 "Other home"
     21 "Public: Govt hospital"
     22 "Public: Govt health center/clinic"
     23 "Public: Govt health post/chps"
     24 "Public: Mobile clinic/outreach"
     26 "Public: Other public sector"
     31 "Private: Hospital/clinic"
     32 "Private: Fp/ppag clinic"
     33 "Private: Mobile clinic/outreach"
     34 "Private: Maternity home"
     36 "Private: Other private med sector"
     96 "Other"
  /Q453B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q454U   
      1 "Hours after birth"
      2 "Days after birth"
      3 "Weeks after birth"
      9 "Special answers"
  /Q454N   
     98 "Don't know"
  /Q455    
     11 "Health personnel: Doctor"
     12 "Health personnel: Nurse/midwife"
     13 "Health personnel: Com  health officer/nurse"
     21 "Other person: Traditional birth attendant"
     22 "Other person: Village health volunteer"
     23 "Other person: Traditional health practitioner"
     96 "Other"
  /Q456    
     11 "Her home"
     12 "Other home"
     21 "Public: Govt hospital"
     22 "Public: Govt health center/clinic"
     23 "Public: Govt health post/chps"
     24 "Public: Mobile clinic/outreach"
     26 "Public: Other public sector"
     31 "Private: Hospital/clinic"
     32 "Private: Fp/ppag clinic"
     33 "Private: Mobile clinic/outreach"
     34 "Private: Maternity home"
     36 "Private: Other private med sector"
     96 "Other"
  /Q457A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q457B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q457C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q457D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q457E   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q501    
   2012 "2012"
   2013 "2013"
   2014 "2014"
   2015 "2015"
   2016 "2016"
   2017 "2017"
   9998 "DK year"
  /Q502A   
      1 "Health of mother"
      2 "Risk of birth defect"
      3 "Fetus not viable"
      4 "No money to take care of baby"
      5 "Too young to have child"
      6 "Not ready to be a mother"
      7 "No one to help me look after the child"
      8 "Wanted to delay childbearing"
      9 "Wanted to space child"
     10 "Wanted to continue schooling"
     11 "Wanted to continue working"
     12 "Wanted no more children"
     13 "Did not love the father"
     14 "Did not want to stay with the father"
     15 "Partner did not want child/denied the pregnancy"
     16 "Father of child died"
     17 "Child's sex"
     18 "Because of rape"
     19 "To avoid shame"
     20 "Afraid of parents"
     21 "Parents insisted"
     96 "Other"
  /Q502B   
      1 "Yes"
      2 "No"
  /Q502C   
   'A                     ' "Health of mother"
   'B                     ' "Risk of birth defect"
   'C                     ' "Fetus not viable"
   'D                     ' "No money to take care of baby"
   'E                     ' "Too young to have child"
   'F                     ' "Not ready to be a mother"
   'G                     ' "No one to help me look after the child"
   'H                     ' "Wanted to delay childbearing"
   'I                     ' "Wanted to space child"
   'J                     ' "Wanted to continue schooling"
   'K                     ' "Wanted to continue working"
   'L                     ' "Wanted no more children"
   'M                     ' "Did not love the father"
   'N                     ' "Did not want to stay with the father"
   'O                     ' "Partner did not want child/denied the pregnancy"
   'P                     ' "Father of child died"
   'Q                     ' "Child's sex"
   'R                     ' "Because of rape"
   'S                     ' "To avoid shame"
   'T                     ' "Afraid of parents"
   'U                     ' "Parents insisted"
   'X                     ' "Other"
  /Q503    
      1 "Favored"
      2 "Opposed"
      3 "Neutral"
      4 "He did not know"
      5 "Don't know/don't remember"
  /Q504    
      1 "Yes"
      2 "No"
  /Q505U   
      1 "Days"
      2 "Weeks"
      9 "Special answers"
  /Q505N   
     98 "Don't know"
  /Q506    
     11 "Drank milk/coffee/alcohol/other liquid with lots of sugar"
     12 "Drank herbal concoction"
     13 "Drank other home remedies"
     14 "Used any herbal enema"
     15 "Inserted herb/object/other substance in the vagina"
     16 "Heavy massage"
     17 "Excessive physical activity"
     18 "Tablets (exact kind unknown)"
     21 "Cytotec tablets (Misoprostol)"
     22 "Mifepristone + Misoprostol (Medabon,etc)"
     23 "IV / Oxytocin"
     31 "D&C / D&E"
     32 "Vacuum aspiration"
     33 "Injection in abdomen (saline instillation)"
     34 "Catheter"
     35 "Other injection"
     96 "Other"
  /Q507    
      1 "Health personnel: Doctor"
      2 "Health personnel: Nurse/midwife"
      3 "Health personnel: Com  health officer/nurse"
      4 "Other person: Pharmacist/chemical seller"
      5 "Other person: Traditional birth attendant"
      6 "Other person: Community health volunteer"
      7 "Other person: Relative/friend"
      8 "Other person: Traditional practitioner"
      9 "No one"
     96 "Other"
  /Q508    
     11 "Public: Govt hospital"
     12 "Public: Govt health center/clinic"
     13 "Public: Govt health post/chps"
     14 "Public: Mobile clinic/outreach"
     16 "Public: Other public sector"
     21 "Private: Hospital/clinic"
     22 "Private: Fp/ppag clinic"
     23 "Private: Mobile clinic/outreach"
     24 "Private: Maternity home"
     25 "Private: Pharmacy/chemist/drug store"
     26 "Private: Other private medical sector"
     31 "Respondent's home"
     32 "Other home"
     33 "TBA's home"
     96 "Other"
  /Q509A   
      1 "Yes"
      2 "No"
  /Q509B   
   'A      ' "Respondent"
   'B      ' "Partner"
   'C      ' "Mother"
   'D      ' "Father"
   'E      ' "Other family member"
   'F      ' "Friend"
   'X      ' "Other"
  /Q510    
      1 "Yes"
      2 "No"
  /Q511    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q512    
      1 "Yes"
      2 "No"
  /Q513    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q514    
      1 "Yes"
      2 "No"
  /Q515    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q516    
      1 "Yes"
      2 "No"
  /Q517    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q518    
      1 "Yes"
      2 "No"
  /Q519    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q520    
      1 "Yes"
      2 "No"
  /Q521    
   9996 "Other problem"
  /Q522    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q523    
      1 "Yes"
      2 "No"
  /Q524    
   9996 "Other problem"
  /Q525    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q526    
      1 "Yes"
      2 "No"
  /Q527    
   9996 "Other problem"
  /Q528    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q529    
      1 "Yes"
      2 "No"
  /Q530    
   9996 "Other problem"
  /Q531    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q532    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q533    
     11 "Drank milk/coffee/alcohol/other liquid with lots of sugar"
     12 "Drank herbal concoction"
     13 "Drank other home remedies"
     14 "Used any herbal enema"
     15 "Inserted herb/object/other substance in the vagina"
     16 "Heavy massage"
     17 "Excessive physical activity"
     18 "Tablets (exact kind unknown)"
     21 "Cytotec tablets (Misoprostol)"
     22 "Mifepristone + Misoprostol (Medabon,etc)"
     23 "IV / Oxytocin"
     31 "D&C / D&E"
     32 "Vacuum aspiration"
     33 "Injection in abdomen (saline instillation)"
     34 "Catheter"
     35 "Other injection"
     96 "Other"
  /Q534    
      1 "Health personnel: Doctor"
      2 "Health personnel: Nurse/midwife"
      3 "Health personnel: Com  health officer/nurse"
      4 "Other person: Pharmacist/chemical seller"
      5 "Other person: Traditional birth attendant"
      6 "Other person: Community health volunteer"
      7 "Other person: Relative/friend"
      8 "Other person: Traditional practitioner"
      9 "No one"
     96 "Other"
  /Q535    
     11 "Public: Govt hospital"
     12 "Public: Govt health center/clinic"
     13 "Public: Govt health post/chps"
     14 "Public: Mobile clinic/outreach"
     16 "Public: Other public sector"
     21 "Private: Hospital/clinic"
     22 "Private: Fp/ppag clinic"
     23 "Private: Mobile clinic/outreach"
     24 "Private: Maternity home"
     25 "Private: Pharmacy/chemist/drug store"
     26 "Private: Other private medical sector"
     31 "Respondent's home"
     32 "Other home"
     33 "TBA's home"
     96 "Other"
  /Q536A   
      1 "Yes"
      2 "No"
  /Q536B   
   'A      ' "Respondent"
   'B      ' "Partner"
   'C      ' "Mother"
   'D      ' "Father"
   'E      ' "Other family member"
   'F      ' "Friend"
   'X      ' "Other"
  /Q537    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q538    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q539B   
      1 "Local"
      2 "General"
      3 "Neither"
      8 "Don't know"
  /Q540    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q541    
      1 "Yes"
      2 "No"
  /Q542    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q543    
      1 "Yes"
      2 "No"
  /Q544    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q545    
      1 "Yes"
      2 "No"
  /Q546    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q547    
      1 "Yes"
      2 "No"
  /Q548    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q549    
      1 "Yes"
      2 "No"
  /Q550    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q551    
      1 "Yes"
      2 "No"
  /Q552    
   9996 "Other problem"
  /Q553    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q554    
      1 "Yes"
      2 "No"
  /Q555    
   9996 "Other problem"
  /Q556    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q557    
      1 "Yes"
      2 "No"
  /Q558    
   9996 "Other problem"
  /Q559    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q560    
      1 "Yes"
      2 "No"
  /Q561    
   9996 "Other problem"
  /Q562    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q563B   
      1 "Yes"
      2 "No"
  /Q564    
   'A   ' "Operation"
   'B   ' "Blood transfusion"
   'C   ' "Antibiotics"
   'X   ' "Other"
  /Q565    
   'A              ' "Public: Govt hospital"
   'B              ' "Public: Govt health center/clinic"
   'C              ' "Public: Govt health post/chps"
   'D              ' "Public: Mobile clinic/outreach"
   'E              ' "Public: Other public sector"
   'F              ' "Private: Hospital/clinic"
   'G              ' "Private: Fp/ppag clinic"
   'H              ' "Private: Mobile clinic/outreach"
   'I              ' "Private: Maternity home"
   'J              ' "Private: Pharmacy/chemist/drug store"
   'K              ' "Private: Other private medical sector"
   'L              ' "Respondent's home"
   'M              ' "Other home"
   'N              ' "TBA's home"
   'X              ' "Other"
  /Q566A   
      1 "Yes"
      2 "No"
  /Q566BU  
      1 "Nights"
      2 "Weeks"
      9 "Special answers"
  /Q566BN  
     98 "Don't know"
  /Q567    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q568    
      1 "Yes"
      2 "No"
      3 "Not yet 6 months"
      8 "Don't know"
  /Q569    
   'A      ' "Abdominal pain"
   'B      ' "Sterility"
   'C      ' "Infection"
   'D      ' "Lack of period"
   'E      ' "Irregular period"
   'F      ' "More painful period"
   'X      ' "Other"
  /Q570    
      1 "Yes"
      2 "No"
  /Q571    
      1 "Female sterilization"
      2 "Male sterilization"
      3 "Iud"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Diaphragm"
     10 "Foam/jelly"
     11 "Lactational amenorrhea method"
     12 "Rhythm method"
     13 "Withdrawal"
     96 "Other"
  /Q572    
      1 "Yes"
      2 "No"
  /Q573    
      1 "Before the abortion"
      2 "After the abortion"
      3 "Both before and after the abortion"
      8 "Don't know"
  /Q574    
      1 "Yes"
      2 "No"
  /Q575    
      1 "Gave method"
      2 "Prescribed a method"
      3 "Gave referral"
      8 "Don't know"
  /Q601    
   2012 "2012"
   2013 "2013"
   2014 "2014"
   2015 "2015"
   2016 "2016"
   2017 "2017"
   9998 "DK year"
  /Q602    
      1 "Accident"
      2 "Ate something"
      3 "Someone hurt me"
      4 "Spontaneous"
      6 "Other"
      8 "Don't know"
  /Q603    
     11 "Public: Govt hospital"
     12 "Public: Govt health center/clinic"
     13 "Public: Govt health post/chps"
     14 "Public: Mobile clinic/outreach"
     16 "Public: Other public sector"
     21 "Private: Hospital/clinic"
     22 "Private: Fp/ppag clinic"
     23 "Private: Mobile clinic/outreach"
     24 "Private: Maternity home"
     25 "Private: Pharmacy/chemist/drug store"
     26 "Private: Other private medical sector"
     31 "Respondent's home"
     32 "Other home"
     33 "TBA's home"
     41 "Workplace"
     51 "Public place"
     96 "Other"
  /Q604A   
      1 "Yes"
      2 "No"
  /Q604B   
   'A        ' "Health personnel: Doctor"
   'B        ' "Health personnel: Nurse/midwife"
   'C        ' "Health personnel: Com  health officer/nurse"
   'D        ' "Other person: Pharmacist/chemical seller"
   'E        ' "Other person: Traditional birth attendant"
   'F        ' "Other person: Community health volunteer"
   'G        ' "Other person: Relative/friend"
   'H        ' "Other person: Traditional practitioner"
   'X        ' "Other"
  /Q604C   
   'A              ' "Public: Govt hospital"
   'B              ' "Public: Govt health center/clinic"
   'C              ' "Public: Govt health post/chps"
   'D              ' "Public: Mobile clinic/outreach"
   'E              ' "Public: Other public sector"
   'F              ' "Private: Hospital/clinic"
   'G              ' "Private: Fp/ppag clinic"
   'H              ' "Private: Mobile clinic/outreach"
   'I              ' "Private: Maternity home"
   'J              ' "Private: Pharmacy/chemist/drug store"
   'K              ' "Private: Other private medical sector"
   'L              ' "Respondent's home"
   'M              ' "Other home"
   'N              ' "TBA's home"
   'X              ' "Other"
  /Q605    
      1 "Yes"
      2 "No"
  /Q606    
      1 "D&c"
      2 "Vacuum aspiration"
      3 "Oxytocin"
      4 "Cytotec tablets (misoprostol)"
      5 "Mifepristone + misoprostol"
      6 "Catheter"
      7 "Tablets for insertion"
      8 "Herbal mixture insertion"
     96 "Other"
     98 "Don't know"
  /Q607    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q608    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q609B   
      1 "Local"
      2 "General"
      3 "Neither"
      8 "Don't know"
  /Q610    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q611    
      1 "Yes"
      2 "No"
  /Q612    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q613    
      1 "Yes"
      2 "No"
  /Q614    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q615    
      1 "Yes"
      2 "No"
  /Q616    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q617    
      1 "Yes"
      2 "No"
  /Q618    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q619    
      1 "Yes"
      2 "No"
  /Q620    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q621    
      1 "Yes"
      2 "No"
  /Q622    
   9996 "Other problem"
  /Q623    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q624    
      1 "Yes"
      2 "No"
  /Q625    
   9996 "Other problem"
  /Q626    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q627    
      1 "Yes"
      2 "No"
  /Q628    
   9996 "Other problem"
  /Q629    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q630    
      1 "Yes"
      2 "No"
  /Q631    
   9996 "Other problem"
  /Q632    
      1 "Mild"
      2 "Moderate"
      3 "Severe"
      8 "Don't know"
  /Q633    
      1 "Yes"
      2 "No"
  /Q634    
   'A   ' "Operation"
   'B   ' "Blood transfusion"
   'C   ' "Antibiotics"
   'X   ' "Other"
  /Q635    
   'A              ' "Public: Govt hospital"
   'B              ' "Public: Govt health center/clinic"
   'C              ' "Public: Govt health post/chps"
   'D              ' "Public: Mobile clinic/outreach"
   'E              ' "Public: Other public sector"
   'F              ' "Private: Hospital/clinic"
   'G              ' "Private: Fp/ppag clinic"
   'H              ' "Private: Mobile clinic/outreach"
   'I              ' "Private: Maternity home"
   'J              ' "Private: Pharmacy/chemist/drug store"
   'K              ' "Private: Other private medical sector"
   'L              ' "Respondent's home"
   'M              ' "Other home"
   'N              ' "TBA's home"
   'X              ' "Other"
  /Q636A   
      1 "Yes"
      2 "No"
  /Q636BU  
      1 "Nights"
      2 "Weeks"
      9 "Special answers"
  /Q636BN  
     98 "Don't know"
  /Q637    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q638    
      1 "Yes"
      2 "No"
      3 "Not yet 6 months"
      8 "Don't know"
  /Q639    
   'A      ' "Abdominal pain"
   'B      ' "Sterility"
   'C      ' "Infection"
   'D      ' "Lack of period"
   'E      ' "Irregular period"
   'F      ' "More painful period"
   'X      ' "Other"
  /Q640    
      1 "Yes"
      2 "No"
  /Q641    
      1 "Female sterilization"
      2 "Male sterilization"
      3 "Iud"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Diaphragm"
     10 "Foam/jelly"
     11 "Lactational amenorrhea method"
     12 "Rhythm method"
     13 "Withdrawal"
     96 "Other"
  /Q642    
      1 "Yes"
      2 "No"
  /Q643    
      1 "Before the miscarriage"
      2 "After the miscarriage"
      3 "Both before and after the miscarriage"
      8 "Don't know"
  /Q644    
      1 "Yes"
      2 "No"
  /Q645    
      1 "Gave method"
      2 "Prescribed a method"
      3 "Gave referral"
      8 "Don't know"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\GH7I\GHCH7IFL.sav'.
