DATA LIST FILE='C:\COUNTRIES\GH7I\GHIQ7IFL.DAT' RECORDS=1
  /
  QHCLUST     1-4   
  QHNUMBER    5-8   
  QLINE       9-10  
  QREGION    11-12  
  QDISTR     13-16  
  QINTD      17-18  
  QINTM      19-20  
  QINTY      21-24  
  QINTNUM    25-28  
  QRESULT    29-29  
  QVISITS    30-30  
  QSUPERV    31-34  
  QLANGQ     35-36  
  QLANGI     37-38  
  QLANGR     39-40  
  QTRANS     41-41  
  QINTC      42-45  
  QINTCD     46-50  
  QWEIGHT    51-58  
  QTYPE      59-59  
  QCONSENT   60-60  
  Q101H      61-62  
  Q101M      63-64  
  Q102       65-66  
  Q103       67-67  
  Q104       68-69  
  Q105M      70-71  
  Q105Y      72-75  
  Q106       76-77  
  Q107       78-78  
  Q108       79-79  
  Q109       80-81  
  Q111       82-82  
  Q113       83-83  
  Q114       84-84  
  Q115       85-85  
  Q116       86-86  
  Q117       87-87  
  Q118       88-88  
  Q119       89-89  
  Q120       90-90  
  Q121       91-91  
  Q122       92-93  
  Q123       94-95  
  Q105C      96-99  
  Q105F     100-100 
  Q106C     101-102 
  Q108A     103-103 
  QWFTOTAL  104-108 
  QWFTYPE   109-113 
  QWFREG    114-118 
  QWFEDUC   119-123 
  QWFWLTH   124-128 
  Q201      129-129 
  Q202      130-130 
  Q203A     131-132 
  Q203B     133-134 
  Q204      135-135 
  Q205A     136-137 
  Q205B     138-139 
  Q206      140-140 
  Q206AA    141-142 
  Q206AB    143-144 
  Q207A     145-145 
  Q207B     146-147 
  Q207C     148-148 
  Q207D     149-150 
  Q207E     151-151 
  Q207F     152-153 
  Q208A     154-155 
  Q208B     156-157 
  Q208C     158-159 
  Q209      160-160 
  Q222      161-161 
  Q224A     162-162 
  Q224AY    163-166 
  Q224B     167-167 
  Q224BY    168-171 
  Q224C     172-172 
  Q224D     173-173 
  Q226      174-174 
  Q227      175-176 
  Q228      177-177 
  Q229      178-178 
  Q230U     179-179 
  Q230N     180-181 
  Q231      182-182 
  Q232      183-183 
  Q233      184-184 
  Q227C     185-188 
  Q227F     189-189 
  Q238F     190-190 
  Q301N$01  191-192 
  Q301N$02  193-194 
  Q301N$03  195-196 
  Q301N$04  197-198 
  Q301N$05  199-200 
  Q301N$06  201-202 
  Q301N$07  203-204 
  Q301N$08  205-206 
  Q301N$09  207-208 
  Q301N$10  209-210 
  Q301N$11  211-212 
  Q301N$12  213-214 
  Q301N$13  215-216 
  Q301N$14  217-218 
  Q301$01   219-219 
  Q301$02   220-220 
  Q301$03   221-221 
  Q301$04   222-222 
  Q301$05   223-223 
  Q301$06   224-224 
  Q301$07   225-225 
  Q301$08   226-226 
  Q301$09   227-227 
  Q301$10   228-228 
  Q301$11   229-229 
  Q301$12   230-230 
  Q301$13   231-231 
  Q301$14   232-232 
  Q303      233-233 
  Q304      234-249  (A)
  Q305      250-250 
  Q306      251-269  (A)
  Q304N     270-271 
  Q577$1    272-272 
  Q577$2    273-273 
  Q578$1    274-274 
  Q578$2    275-275 
  Q579$1    276-276 
  Q579$2    277-277 
  Q580$1    278-296  (A)
  Q580$2    297-315  (A)
  Q581$1    316-316 
  Q581$2    317-317 
  Q582$1    318-328  (A)
  Q582$2    329-339  (A)
  Q701      340-340 
  Q702      341-341 
  Q703      342-342 
  Q704      343-343 
  Q705      344-345 
  Q706      346-346 
  Q707      347-348 
  Q708      349-350 
  Q709      351-351 
  Q710M     352-353 
  Q710Y     354-357 
  Q711      358-359 
  Q713      360-361 
  Q714U     362-362 
  Q714N     363-364 
  Q710C     365-368 
  Q710F     369-369 
  Q711C     370-371 
  Q713F     372-372 
  Q714F     373-373 
  Q813$01   374-375 
  Q813$02   376-377 
  Q813$03   378-379 
  Q813$04   380-381 
  Q813$05   382-383 
  Q813$06   384-385 
  Q813$07   386-387 
  Q813$08   388-389 
  Q813$09   390-391 
  Q813$10   392-393 
  Q813$11   394-395 
  Q813$12   396-397 
  Q813$13   398-399 
  Q813$14   400-401 
  Q813$15   402-403 
  Q813$16   404-405 
  Q813$17   406-407 
  Q813$18   408-409 
  Q813$19   410-411 
  Q813$20   412-413 
  Q814$01   414-414 
  Q814$02   415-415 
  Q814$03   416-416 
  Q814$04   417-417 
  Q814$05   418-418 
  Q814$06   419-419 
  Q814$07   420-420 
  Q814$08   421-421 
  Q814$09   422-422 
  Q814$10   423-423 
  Q814$11   424-424 
  Q814$12   425-425 
  Q814$13   426-426 
  Q814$14   427-427 
  Q814$15   428-428 
  Q814$16   429-429 
  Q814$17   430-430 
  Q814$18   431-431 
  Q814$19   432-432 
  Q814$20   433-433 
  Q815$01   434-434 
  Q815$02   435-435 
  Q815$03   436-436 
  Q815$04   437-437 
  Q815$05   438-438 
  Q815$06   439-439 
  Q815$07   440-440 
  Q815$08   441-441 
  Q815$09   442-442 
  Q815$10   443-443 
  Q815$11   444-444 
  Q815$12   445-445 
  Q815$13   446-446 
  Q815$14   447-447 
  Q815$15   448-448 
  Q815$16   449-449 
  Q815$17   450-450 
  Q815$18   451-451 
  Q815$19   452-452 
  Q815$20   453-453 
  Q816$01   454-455 
  Q816$02   456-457 
  Q816$03   458-459 
  Q816$04   460-461 
  Q816$05   462-463 
  Q816$06   464-465 
  Q816$07   466-467 
  Q816$08   468-469 
  Q816$09   470-471 
  Q816$10   472-473 
  Q816$11   474-475 
  Q816$12   476-477 
  Q816$13   478-479 
  Q816$14   480-481 
  Q816$15   482-483 
  Q816$16   484-485 
  Q816$17   486-487 
  Q816$18   488-489 
  Q816$19   490-491 
  Q816$20   492-493 
  Q817$01   494-495 
  Q817$02   496-497 
  Q817$03   498-499 
  Q817$04   500-501 
  Q817$05   502-503 
  Q817$06   504-505 
  Q817$07   506-507 
  Q817$08   508-509 
  Q817$09   510-511 
  Q817$10   512-513 
  Q817$11   514-515 
  Q817$12   516-517 
  Q817$13   518-519 
  Q817$14   520-521 
  Q817$15   522-523 
  Q817$16   524-525 
  Q817$17   526-527 
  Q817$18   528-529 
  Q817$19   530-531 
  Q817$20   532-533 
  Q818$01   534-535 
  Q818$02   536-537 
  Q818$03   538-539 
  Q818$04   540-541 
  Q818$05   542-543 
  Q818$06   544-545 
  Q818$07   546-547 
  Q818$08   548-549 
  Q818$09   550-551 
  Q818$10   552-553 
  Q818$11   554-555 
  Q818$12   556-557 
  Q818$13   558-559 
  Q818$14   560-561 
  Q818$15   562-563 
  Q818$16   564-565 
  Q818$17   566-567 
  Q818$18   568-569 
  Q818$19   570-571 
  Q818$20   572-573 
  Q819$01   574-574 
  Q819$02   575-575 
  Q819$03   576-576 
  Q819$04   577-577 
  Q819$05   578-578 
  Q819$06   579-579 
  Q819$07   580-580 
  Q819$08   581-581 
  Q819$09   582-582 
  Q819$10   583-583 
  Q819$11   584-584 
  Q819$12   585-585 
  Q819$13   586-586 
  Q819$14   587-587 
  Q819$15   588-588 
  Q819$16   589-589 
  Q819$17   590-590 
  Q819$18   591-591 
  Q819$19   592-592 
  Q819$20   593-593 
  Q820$01   594-594 
  Q820$02   595-595 
  Q820$03   596-596 
  Q820$04   597-597 
  Q820$05   598-598 
  Q820$06   599-599 
  Q820$07   600-600 
  Q820$08   601-601 
  Q820$09   602-602 
  Q820$10   603-603 
  Q820$11   604-604 
  Q820$12   605-605 
  Q820$13   606-606 
  Q820$14   607-607 
  Q820$15   608-608 
  Q820$16   609-609 
  Q820$17   610-610 
  Q820$18   611-611 
  Q820$19   612-612 
  Q820$20   613-613 
  Q821$01   614-614 
  Q821$02   615-615 
  Q821$03   616-616 
  Q821$04   617-617 
  Q821$05   618-618 
  Q821$06   619-619 
  Q821$07   620-620 
  Q821$08   621-621 
  Q821$09   622-622 
  Q821$10   623-623 
  Q821$11   624-624 
  Q821$12   625-625 
  Q821$13   626-626 
  Q821$14   627-627 
  Q821$15   628-628 
  Q821$16   629-629 
  Q821$17   630-630 
  Q821$18   631-631 
  Q821$19   632-632 
  Q821$20   633-633 
  Q822$01   634-635 
  Q822$02   636-637 
  Q822$03   638-639 
  Q822$04   640-641 
  Q822$05   642-643 
  Q822$06   644-645 
  Q822$07   646-647 
  Q822$08   648-649 
  Q822$09   650-651 
  Q822$10   652-653 
  Q822$11   654-655 
  Q822$12   656-657 
  Q822$13   658-659 
  Q822$14   660-661 
  Q822$15   662-663 
  Q822$16   664-665 
  Q822$17   666-667 
  Q822$18   668-669 
  Q822$19   670-671 
  Q822$20   672-673 
  Q823$01   674-674 
  Q823$02   675-675 
  Q823$03   676-676 
  Q823$04   677-677 
  Q823$05   678-678 
  Q823$06   679-679 
  Q823$07   680-680 
  Q823$08   681-681 
  Q823$09   682-682 
  Q823$10   683-683 
  Q823$11   684-684 
  Q823$12   685-685 
  Q823$13   686-686 
  Q823$14   687-687 
  Q823$15   688-688 
  Q823$16   689-689 
  Q823$17   690-690 
  Q823$18   691-691 
  Q823$19   692-692 
  Q823$20   693-693 
  Q824$01   694-694 
  Q824$02   695-695 
  Q824$03   696-696 
  Q824$04   697-697 
  Q824$05   698-698 
  Q824$06   699-699 
  Q824$07   700-700 
  Q824$08   701-701 
  Q824$09   702-702 
  Q824$10   703-703 
  Q824$11   704-704 
  Q824$12   705-705 
  Q824$13   706-706 
  Q824$14   707-707 
  Q824$15   708-708 
  Q824$16   709-709 
  Q824$17   710-710 
  Q824$18   711-711 
  Q824$19   712-712 
  Q824$20   713-713 
  Q816C$01  714-717 
  Q816C$02  718-721 
  Q816C$03  722-725 
  Q816C$04  726-729 
  Q816C$05  730-733 
  Q816C$06  734-737 
  Q816C$07  738-741 
  Q816C$08  742-745 
  Q816C$09  746-749 
  Q816C$10  750-753 
  Q816C$11  754-757 
  Q816C$12  758-761 
  Q816C$13  762-765 
  Q816C$14  766-769 
  Q816C$15  770-773 
  Q816C$16  774-777 
  Q816C$17  778-781 
  Q816C$18  782-785 
  Q816C$19  786-789 
  Q816C$20  790-793 
  Q817C$01  794-797 
  Q817C$02  798-801 
  Q817C$03  802-805 
  Q817C$04  806-809 
  Q817C$05  810-813 
  Q817C$06  814-817 
  Q817C$07  818-821 
  Q817C$08  822-825 
  Q817C$09  826-829 
  Q817C$10  830-833 
  Q817C$11  834-837 
  Q817C$12  838-841 
  Q817C$13  842-845 
  Q817C$14  846-849 
  Q817C$15  850-853 
  Q817C$16  854-857 
  Q817C$17  858-861 
  Q817C$18  862-865 
  Q817C$19  866-869 
  Q817C$20  870-873 
  Q901A     874-874 
  Q901B     875-875 
  Q901C     876-876 
  Q901D     877-877 
  Q902      878-878 
  Q903      879-879 
  Q904      880-884  (A)
  Q905A     885-885 
  Q905B     886-886 
  Q905C     887-887 
  Q905D     888-888 
  Q905E     889-889 
  Q905F     890-890 
  Q906      891-891 
  Q908      892-892 
  Q909A     893-893 
  Q909B     894-894 
  Q909C     895-895 
  Q909D     896-896 
  Q909E     897-897 
  Q911      898-898 
  Q912A     899-899 
  Q912B     900-900 
  Q912C     901-901 
  Q912D     902-902 
  Q912E     903-903 
  Q914      904-904 
  Q916      905-905 
  Q917      906-906 
  Q918      907-907 
  Q919      908-908 
  Q920      909-909 
  Q921      910-910 
  Q922      911-911 
  Q923      912-912 
  Q924      913-913 
  Q925H     914-915 
  Q925M     916-917 
 .
VARIABLE LABELS
   QHCLUST  "Cluster number"
  /QHNUMBER "Household number"
  /QLINE    "Individual line number"
  /QREGION  "Region"
  /QDISTR   "District"
  /QINTD    "Day of interview"
  /QINTM    "Month of interview"
  /QINTY    "Year of interview"
  /QINTNUM  "Interviewer number"
  /QRESULT  "Result of individual interview"
  /QVISITS  "Total number of visits"
  /QSUPERV  "Supervisor number"
  /QLANGQ   "Language of questionnaire"
  /QLANGI   "Language of interview"
  /QLANGR   "Language of respondent"
  /QTRANS   "Translator used"
  /QINTC    "Date of interview (CMC)"
  /QINTCD   "Date of interview Century Day Code (CDC)"
  /QWEIGHT  "Sample weight (6 decimals)"
  /QTYPE    "Type of place of residence"
  /QCONSENT "Consent agreement"
  /Q101H    "Start of interview (hour)"
  /Q101M    "Start of interview (minutes)"
  /Q102     "Time living in place of interview"
  /Q103     "Lived in a city/town or rural area"
  /Q104     "Region lived before moved to place of interview"
  /Q105M    "Month of birth"
  /Q105Y    "Year of birth"
  /Q106     "Current age of respondent"
  /Q107     "Ever attended school"
  /Q108     "Highest educational level"
  /Q109     "Highest grade/form/year at that level"
  /Q111     "Sentence read"
  /Q113     "Reads newspaper"
  /Q114     "Listens to radio"
  /Q115     "Watches television"
  /Q116     "Own a mobile telephone"
  /Q117     "Use mobile telephone for financial transactions"
  /Q118     "Have a bank or other financial account"
  /Q119     "Have ever used the internet"
  /Q120     "Have used the internet last 12 months"
  /Q121     "How often used internet the last month"
  /Q122     "Religion"
  /Q123     "Ethnicity"
  /Q105C    "Date of birth (CMC)"
  /Q105F    "Date flag for Q105C"
  /Q106C    "Age of respondent calculated"
  /Q108A    "Highest educational level"
  /QWFTOTAL "All woman factor - total"
  /QWFTYPE  "All woman factor - urban/rural"
  /QWFREG   "All woman factor - regional"
  /QWFEDUC  "All woman factor - educational"
  /QWFWLTH  "All woman factor - wealth index"
  /Q201     "Ever given birth"
  /Q202     "Sons or daughters living with"
  /Q203A    "Sons at home"
  /Q203B    "Daughters at home"
  /Q204     "Sons or daughters living away"
  /Q205A    "Sons living elsewhere"
  /Q205B    "Daughters living elsewhere"
  /Q206     "Sons or daughters who died"
  /Q206AA   "Boys who died"
  /Q206AB   "Girls who died"
  /Q207A    "Ever had miscarriage"
  /Q207B    "Number of miscarriages"
  /Q207C    "Ever had abortion"
  /Q207D    "Number of abortions"
  /Q207E    "Ever had a stillbirth"
  /Q207F    "Number of stillbirths"
  /Q208A    "Total births"
  /Q208B    "Total pregnancy outcomes"
  /Q208C    "Total pregnancies with no live births"
  /Q209     "Probe to pregnancies"
  /Q222     "Birth between last & interview"
  /Q224A    "Abortions since January 2012"
  /Q224AY   "Year of most recent abortion in 2012 or after"
  /Q224B    "Miscarriages since January 2012"
  /Q224BY   "Year of most recent miscarriage in 2012 or after"
  /Q224C    "Births since January 2012"
  /Q224D    "Stillbirths since January 2012"
  /Q226     "Currently pregnant"
  /Q227     "Duration of current pregnancy"
  /Q228     "Wanted pregnancy at that time"
  /Q229     "Wanted pregnancy"
  /Q230U    "Time since last period (unit)"
  /Q230N    "Time since last period (number)"
  /Q231     "Knowledge of fertile period"
  /Q232     "When is the fertile period"
  /Q233     "After birth, can a woman get pregnant before period returns"
  /Q227C    "Date of conception (CMC)"
  /Q227F    "Date flag for Q227C"
  /Q238F    "Flag for Q239"
  /Q301N$01 "Contraceptive method"
  /Q301N$02 "Contraceptive method"
  /Q301N$03 "Contraceptive method"
  /Q301N$04 "Contraceptive method"
  /Q301N$05 "Contraceptive method"
  /Q301N$06 "Contraceptive method"
  /Q301N$07 "Contraceptive method"
  /Q301N$08 "Contraceptive method"
  /Q301N$09 "Contraceptive method"
  /Q301N$10 "Contraceptive method"
  /Q301N$11 "Contraceptive method"
  /Q301N$12 "Contraceptive method"
  /Q301N$13 "Contraceptive method"
  /Q301N$14 "Contraceptive method"
  /Q301$01  "Heard of method"
  /Q301$02  "Heard of method"
  /Q301$03  "Heard of method"
  /Q301$04  "Heard of method"
  /Q301$05  "Heard of method"
  /Q301$06  "Heard of method"
  /Q301$07  "Heard of method"
  /Q301$08  "Heard of method"
  /Q301$09  "Heard of method"
  /Q301$10  "Heard of method"
  /Q301$11  "Heard of method"
  /Q301$12  "Heard of method"
  /Q301$13  "Heard of method"
  /Q301$14  "Heard of method"
  /Q303     "Currently using any method"
  /Q304     "Current contraceptive method"
  /Q305     "Know source for FP"
  /Q306     "Place known for FP"
  /Q304N    "Current contraceptive method (major method)"
  /Q577$1   "Ever heard of abortion"
  /Q577$2   "Ever heard of abortion"
  /Q578$1   "Could decide on your own to get an abortion"
  /Q578$2   "Could decide on your own to get an abortion"
  /Q579$1   "Knows where to get an abortion"
  /Q579$2   "Knows where to get an abortion"
  /Q580$1   "Where to go for abortion"
  /Q580$2   "Where to go for abortion"
  /Q581$1   "Abortion legal in Ghana"
  /Q581$2   "Abortion legal in Ghana"
  /Q582$1   "Conditions of legal abortion in Ghana"
  /Q582$2   "Conditions of legal abortion in Ghana"
  /Q701     "Currently in union"
  /Q702     "Have ever been married or lived with a man"
  /Q703     "Current marital status"
  /Q704     "Partner living with respondent"
  /Q705     "Line number of husband"
  /Q706     "Husband has other wives"
  /Q707     "Number of wives including respondent"
  /Q708     "Wife's rank number"
  /Q709     "In union more than once"
  /Q710M    "Time of first union (month)"
  /Q710Y    "Time of first union (year)"
  /Q711     "Age at first union"
  /Q713     "Age at first intercourse"
  /Q714U    "Time since last intercourse (unit)"
  /Q714N    "Time since last intercourse (number)"
  /Q710C    "Date of first union (CMC)"
  /Q710F    "Date flag for Q710C"
  /Q711C    "Age at first union (calculated)"
  /Q713F    "Flag for Q713"
  /Q714F    "Flag for Q714"
  /Q813$01  "Column number"
  /Q813$02  "Column number"
  /Q813$03  "Column number"
  /Q813$04  "Column number"
  /Q813$05  "Column number"
  /Q813$06  "Column number"
  /Q813$07  "Column number"
  /Q813$08  "Column number"
  /Q813$09  "Column number"
  /Q813$10  "Column number"
  /Q813$11  "Column number"
  /Q813$12  "Column number"
  /Q813$13  "Column number"
  /Q813$14  "Column number"
  /Q813$15  "Column number"
  /Q813$16  "Column number"
  /Q813$17  "Column number"
  /Q813$18  "Column number"
  /Q813$19  "Column number"
  /Q813$20  "Column number"
  /Q814$01  "Sex of sibling"
  /Q814$02  "Sex of sibling"
  /Q814$03  "Sex of sibling"
  /Q814$04  "Sex of sibling"
  /Q814$05  "Sex of sibling"
  /Q814$06  "Sex of sibling"
  /Q814$07  "Sex of sibling"
  /Q814$08  "Sex of sibling"
  /Q814$09  "Sex of sibling"
  /Q814$10  "Sex of sibling"
  /Q814$11  "Sex of sibling"
  /Q814$12  "Sex of sibling"
  /Q814$13  "Sex of sibling"
  /Q814$14  "Sex of sibling"
  /Q814$15  "Sex of sibling"
  /Q814$16  "Sex of sibling"
  /Q814$17  "Sex of sibling"
  /Q814$18  "Sex of sibling"
  /Q814$19  "Sex of sibling"
  /Q814$20  "Sex of sibling"
  /Q815$01  "Sibling alive"
  /Q815$02  "Sibling alive"
  /Q815$03  "Sibling alive"
  /Q815$04  "Sibling alive"
  /Q815$05  "Sibling alive"
  /Q815$06  "Sibling alive"
  /Q815$07  "Sibling alive"
  /Q815$08  "Sibling alive"
  /Q815$09  "Sibling alive"
  /Q815$10  "Sibling alive"
  /Q815$11  "Sibling alive"
  /Q815$12  "Sibling alive"
  /Q815$13  "Sibling alive"
  /Q815$14  "Sibling alive"
  /Q815$15  "Sibling alive"
  /Q815$16  "Sibling alive"
  /Q815$17  "Sibling alive"
  /Q815$18  "Sibling alive"
  /Q815$19  "Sibling alive"
  /Q815$20  "Sibling alive"
  /Q816$01  "Age of sibling"
  /Q816$02  "Age of sibling"
  /Q816$03  "Age of sibling"
  /Q816$04  "Age of sibling"
  /Q816$05  "Age of sibling"
  /Q816$06  "Age of sibling"
  /Q816$07  "Age of sibling"
  /Q816$08  "Age of sibling"
  /Q816$09  "Age of sibling"
  /Q816$10  "Age of sibling"
  /Q816$11  "Age of sibling"
  /Q816$12  "Age of sibling"
  /Q816$13  "Age of sibling"
  /Q816$14  "Age of sibling"
  /Q816$15  "Age of sibling"
  /Q816$16  "Age of sibling"
  /Q816$17  "Age of sibling"
  /Q816$18  "Age of sibling"
  /Q816$19  "Age of sibling"
  /Q816$20  "Age of sibling"
  /Q817$01  "Years since siblings death"
  /Q817$02  "Years since siblings death"
  /Q817$03  "Years since siblings death"
  /Q817$04  "Years since siblings death"
  /Q817$05  "Years since siblings death"
  /Q817$06  "Years since siblings death"
  /Q817$07  "Years since siblings death"
  /Q817$08  "Years since siblings death"
  /Q817$09  "Years since siblings death"
  /Q817$10  "Years since siblings death"
  /Q817$11  "Years since siblings death"
  /Q817$12  "Years since siblings death"
  /Q817$13  "Years since siblings death"
  /Q817$14  "Years since siblings death"
  /Q817$15  "Years since siblings death"
  /Q817$16  "Years since siblings death"
  /Q817$17  "Years since siblings death"
  /Q817$18  "Years since siblings death"
  /Q817$19  "Years since siblings death"
  /Q817$20  "Years since siblings death"
  /Q818$01  "Age of sibling at death"
  /Q818$02  "Age of sibling at death"
  /Q818$03  "Age of sibling at death"
  /Q818$04  "Age of sibling at death"
  /Q818$05  "Age of sibling at death"
  /Q818$06  "Age of sibling at death"
  /Q818$07  "Age of sibling at death"
  /Q818$08  "Age of sibling at death"
  /Q818$09  "Age of sibling at death"
  /Q818$10  "Age of sibling at death"
  /Q818$11  "Age of sibling at death"
  /Q818$12  "Age of sibling at death"
  /Q818$13  "Age of sibling at death"
  /Q818$14  "Age of sibling at death"
  /Q818$15  "Age of sibling at death"
  /Q818$16  "Age of sibling at death"
  /Q818$17  "Age of sibling at death"
  /Q818$18  "Age of sibling at death"
  /Q818$19  "Age of sibling at death"
  /Q818$20  "Age of sibling at death"
  /Q819$01  "Died while pregnant"
  /Q819$02  "Died while pregnant"
  /Q819$03  "Died while pregnant"
  /Q819$04  "Died while pregnant"
  /Q819$05  "Died while pregnant"
  /Q819$06  "Died while pregnant"
  /Q819$07  "Died while pregnant"
  /Q819$08  "Died while pregnant"
  /Q819$09  "Died while pregnant"
  /Q819$10  "Died while pregnant"
  /Q819$11  "Died while pregnant"
  /Q819$12  "Died while pregnant"
  /Q819$13  "Died while pregnant"
  /Q819$14  "Died while pregnant"
  /Q819$15  "Died while pregnant"
  /Q819$16  "Died while pregnant"
  /Q819$17  "Died while pregnant"
  /Q819$18  "Died while pregnant"
  /Q819$19  "Died while pregnant"
  /Q819$20  "Died while pregnant"
  /Q820$01  "Died during childbirth"
  /Q820$02  "Died during childbirth"
  /Q820$03  "Died during childbirth"
  /Q820$04  "Died during childbirth"
  /Q820$05  "Died during childbirth"
  /Q820$06  "Died during childbirth"
  /Q820$07  "Died during childbirth"
  /Q820$08  "Died during childbirth"
  /Q820$09  "Died during childbirth"
  /Q820$10  "Died during childbirth"
  /Q820$11  "Died during childbirth"
  /Q820$12  "Died during childbirth"
  /Q820$13  "Died during childbirth"
  /Q820$14  "Died during childbirth"
  /Q820$15  "Died during childbirth"
  /Q820$16  "Died during childbirth"
  /Q820$17  "Died during childbirth"
  /Q820$18  "Died during childbirth"
  /Q820$19  "Died during childbirth"
  /Q820$20  "Died during childbirth"
  /Q821$01  "Died within 2 months of delivery"
  /Q821$02  "Died within 2 months of delivery"
  /Q821$03  "Died within 2 months of delivery"
  /Q821$04  "Died within 2 months of delivery"
  /Q821$05  "Died within 2 months of delivery"
  /Q821$06  "Died within 2 months of delivery"
  /Q821$07  "Died within 2 months of delivery"
  /Q821$08  "Died within 2 months of delivery"
  /Q821$09  "Died within 2 months of delivery"
  /Q821$10  "Died within 2 months of delivery"
  /Q821$11  "Died within 2 months of delivery"
  /Q821$12  "Died within 2 months of delivery"
  /Q821$13  "Died within 2 months of delivery"
  /Q821$14  "Died within 2 months of delivery"
  /Q821$15  "Died within 2 months of delivery"
  /Q821$16  "Died within 2 months of delivery"
  /Q821$17  "Died within 2 months of delivery"
  /Q821$18  "Died within 2 months of delivery"
  /Q821$19  "Died within 2 months of delivery"
  /Q821$20  "Died within 2 months of delivery"
  /Q822$01  "Days after end of pregnancy/childbirth sister died"
  /Q822$02  "Days after end of pregnancy/childbirth sister died"
  /Q822$03  "Days after end of pregnancy/childbirth sister died"
  /Q822$04  "Days after end of pregnancy/childbirth sister died"
  /Q822$05  "Days after end of pregnancy/childbirth sister died"
  /Q822$06  "Days after end of pregnancy/childbirth sister died"
  /Q822$07  "Days after end of pregnancy/childbirth sister died"
  /Q822$08  "Days after end of pregnancy/childbirth sister died"
  /Q822$09  "Days after end of pregnancy/childbirth sister died"
  /Q822$10  "Days after end of pregnancy/childbirth sister died"
  /Q822$11  "Days after end of pregnancy/childbirth sister died"
  /Q822$12  "Days after end of pregnancy/childbirth sister died"
  /Q822$13  "Days after end of pregnancy/childbirth sister died"
  /Q822$14  "Days after end of pregnancy/childbirth sister died"
  /Q822$15  "Days after end of pregnancy/childbirth sister died"
  /Q822$16  "Days after end of pregnancy/childbirth sister died"
  /Q822$17  "Days after end of pregnancy/childbirth sister died"
  /Q822$18  "Days after end of pregnancy/childbirth sister died"
  /Q822$19  "Days after end of pregnancy/childbirth sister died"
  /Q822$20  "Days after end of pregnancy/childbirth sister died"
  /Q823$01  "Death due to violence"
  /Q823$02  "Death due to violence"
  /Q823$03  "Death due to violence"
  /Q823$04  "Death due to violence"
  /Q823$05  "Death due to violence"
  /Q823$06  "Death due to violence"
  /Q823$07  "Death due to violence"
  /Q823$08  "Death due to violence"
  /Q823$09  "Death due to violence"
  /Q823$10  "Death due to violence"
  /Q823$11  "Death due to violence"
  /Q823$12  "Death due to violence"
  /Q823$13  "Death due to violence"
  /Q823$14  "Death due to violence"
  /Q823$15  "Death due to violence"
  /Q823$16  "Death due to violence"
  /Q823$17  "Death due to violence"
  /Q823$18  "Death due to violence"
  /Q823$19  "Death due to violence"
  /Q823$20  "Death due to violence"
  /Q824$01  "Death due to accident"
  /Q824$02  "Death due to accident"
  /Q824$03  "Death due to accident"
  /Q824$04  "Death due to accident"
  /Q824$05  "Death due to accident"
  /Q824$06  "Death due to accident"
  /Q824$07  "Death due to accident"
  /Q824$08  "Death due to accident"
  /Q824$09  "Death due to accident"
  /Q824$10  "Death due to accident"
  /Q824$11  "Death due to accident"
  /Q824$12  "Death due to accident"
  /Q824$13  "Death due to accident"
  /Q824$14  "Death due to accident"
  /Q824$15  "Death due to accident"
  /Q824$16  "Death due to accident"
  /Q824$17  "Death due to accident"
  /Q824$18  "Death due to accident"
  /Q824$19  "Death due to accident"
  /Q824$20  "Death due to accident"
  /Q816C$01 "CMC date of birth of sibling"
  /Q816C$02 "CMC date of birth of sibling"
  /Q816C$03 "CMC date of birth of sibling"
  /Q816C$04 "CMC date of birth of sibling"
  /Q816C$05 "CMC date of birth of sibling"
  /Q816C$06 "CMC date of birth of sibling"
  /Q816C$07 "CMC date of birth of sibling"
  /Q816C$08 "CMC date of birth of sibling"
  /Q816C$09 "CMC date of birth of sibling"
  /Q816C$10 "CMC date of birth of sibling"
  /Q816C$11 "CMC date of birth of sibling"
  /Q816C$12 "CMC date of birth of sibling"
  /Q816C$13 "CMC date of birth of sibling"
  /Q816C$14 "CMC date of birth of sibling"
  /Q816C$15 "CMC date of birth of sibling"
  /Q816C$16 "CMC date of birth of sibling"
  /Q816C$17 "CMC date of birth of sibling"
  /Q816C$18 "CMC date of birth of sibling"
  /Q816C$19 "CMC date of birth of sibling"
  /Q816C$20 "CMC date of birth of sibling"
  /Q817C$01 "CMC date of death of sibling"
  /Q817C$02 "CMC date of death of sibling"
  /Q817C$03 "CMC date of death of sibling"
  /Q817C$04 "CMC date of death of sibling"
  /Q817C$05 "CMC date of death of sibling"
  /Q817C$06 "CMC date of death of sibling"
  /Q817C$07 "CMC date of death of sibling"
  /Q817C$08 "CMC date of death of sibling"
  /Q817C$09 "CMC date of death of sibling"
  /Q817C$10 "CMC date of death of sibling"
  /Q817C$11 "CMC date of death of sibling"
  /Q817C$12 "CMC date of death of sibling"
  /Q817C$13 "CMC date of death of sibling"
  /Q817C$14 "CMC date of death of sibling"
  /Q817C$15 "CMC date of death of sibling"
  /Q817C$16 "CMC date of death of sibling"
  /Q817C$17 "CMC date of death of sibling"
  /Q817C$18 "CMC date of death of sibling"
  /Q817C$19 "CMC date of death of sibling"
  /Q817C$20 "CMC date of death of sibling"
  /Q901A    "Care factors: Getting permission"
  /Q901B    "Care factors: Getting money needed for treatment"
  /Q901C    "Care factors: Distance, no nearby health facility"
  /Q901D    "Care factors: Not wanting to go alone"
  /Q902     "Registered with any health insurance"
  /Q903     "Covered by health insurance"
  /Q904     "Type of health insurance"
  /Q905A    "Insurance coverage: Antenatal"
  /Q905B    "Insurance coverage: Childbirth"
  /Q905C    "Insurance coverage: Postnatal care for mother"
  /Q905D    "Insurance coverage: Postnatal care for child"
  /Q905E    "Insurance coverage: Cash benefits"
  /Q905F    "Insurance coverage: Other maternity benefits"
  /Q906     "Pay for drugs/services"
  /Q908     "Asked to make any payment during antenatal care"
  /Q909A    "Asked to pay for services during antenatal care"
  /Q909B    "Asked to pay for drugs during antenatal care"
  /Q909C    "Asked to pay for laboratory tests during antenatal care"
  /Q909D    "Asked to pay for other supplies during antenatal care"
  /Q909E    "Asked to pay for anything else during antenatal care"
  /Q911     "Asked to make any payment during delivery"
  /Q912A    "Asked to pay for services during delivery"
  /Q912B    "Asked to pay for drugs during delivery"
  /Q912C    "Asked to pay for laboratory tests during delivery"
  /Q912D    "Asked to pay for other supplies during delivery"
  /Q912E    "Asked to pay for anything else during delivery"
  /Q914     "Asked to make any payment for checks on woman health after given birth"
  /Q916     "Asked to make any payment for checks on child health after given birth"
  /Q917     "Wears glasses or contact lens"
  /Q918     "Type of seeing difficulty using glasses or contact lens"
  /Q919     "Type of seeing difficulty"
  /Q920     "Type of hearing difficulty"
  /Q921     "Type of communication difficulty"
  /Q922     "Type of remembering difficulty"
  /Q923     "Type of walking/climbing steps difficulty"
  /Q924     "Type of washing/cleaning difficulty"
  /Q925H    "End of interview (hour)"
  /Q925M    "End of interview (minutes)"
 .
MISSING VALUE
   Q305     (9)
  /Q908     (9)
  /Q911     (9)
 .
VALUE LABELS
   QREGION 
      1 "Western"
      2 "Central"
      3 "Greater accra"
      4 "Volta"
      5 "Eastern"
      6 "Ashanti"
      7 "Brong ahafo"
      8 "Northern"
      9 "Upper east"
     10 "Upper west"
  /QINTM   
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
  /QRESULT 
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
  /QLANGQ  
      0 "English"
      1 "Akan"
      2 "Ga"
      3 "Ewe"
  /QLANGI  
      0 "English"
      1 "Akan"
      2 "Ga"
      3 "Ewe"
      4 "Guan"
      5 "Mole-dagbani"
      6 "Grusi"
      7 "Gurma"
      8 "Mande"
     96 "Other"
  /QLANGR  
      0 "English"
      1 "Akan"
      2 "Ga"
      3 "Ewe"
      4 "Guan"
      5 "Mole-dagbani"
      6 "Grusi"
      7 "Gurma"
      8 "Mande"
     96 "Other"
  /QTRANS  
      1 "Yes"
      2 "No"
  /QTYPE   
      1 "Urban"
      2 "Rural"
  /QCONSENT
      1 "Respondent agrees to be interviewed"
      2 "Respondent does not agree to be interviewed"
  /Q101H   
     97 "Inconsistent"
  /Q101M   
     97 "Inconsistent"
  /Q102    
      0 "Less than one year"
     95 "Always"
     96 "Visitor"
  /Q103    
      1 "City"
      2 "Town"
      3 "Rural area"
  /Q104    
      1 "Western"
      2 "Central"
      3 "Greater accra"
      4 "Volta"
      5 "Eastern"
      6 "Ashanti"
      7 "Brong ahafo"
      8 "Northern"
      9 "Upper east"
     10 "Upper west"
     96 "Outside of ghana"
  /Q105M   
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Don't know month"
  /Q105Y   
   9998 "Don't know year"
  /Q106    
     98 "DK"
  /Q107    
      1 "Yes"
      2 "No"
  /Q108    
      1 "Primary"
      2 "Middle"
      3 "Jss/jhs"
      4 "Secondary/Tech/Voc/Comm"
      5 "Sss/Shs/Tech/Voc/Comm"
      6 "Higher"
  /Q109    
      0 "Less than one year"
  /Q111    
      1 "Cannot read at all"
      2 "Able to read only part of the sentence"
      3 "Able to read whole sentence"
      4 "No card with required language"
      5 "Blind/visually impaired"
  /Q113    
      1 "At least once a week"
      2 "Less than once a week"
      3 "Not at all"
  /Q114    
      1 "At least once a week"
      2 "Less than once a week"
      3 "Not at all"
  /Q115    
      1 "At least once a week"
      2 "Less than once a week"
      3 "Not at all"
  /Q116    
      1 "Yes"
      2 "No"
  /Q117    
      1 "Yes"
      2 "No"
  /Q118    
      1 "Yes"
      2 "No"
  /Q119    
      1 "Yes"
      2 "No"
  /Q120    
      1 "Yes"
      2 "No"
  /Q121    
      1 "Almost every day"
      2 "At least once a week"
      3 "Less than once a week"
      4 "Not at all"
  /Q122    
      1 "Catholic"
      2 "Anglican"
      3 "Methodist"
      4 "Presbyterian"
      5 "Pentecostal/charismatic"
      6 "Other christian"
      7 "Islam"
      8 "Traditional/spiritualist"
      9 "No religion"
     96 "Other"
  /Q123    
      1 "Akan"
      2 "Ga/dangme"
      3 "Ewe"
      4 "Guan"
      5 "Mole-dagbani"
      6 "Grusi"
      7 "Gurma"
      8 "Mande"
     96 "Other"
  /Q105F   
      1 "Month and year"
      2 "Month and age -y imp"
      3 "Year and age - m imp"
      4 "Y & age - y ignored"
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
  /Q108A   
      0 "No education"
      1 "Primary incomplete"
      2 "Primary complete"
      3 "Secondary incomplete"
      4 "Secondary complete"
      5 "Higher"
  /QWFTOTAL
      0 "NotAppl"
  /QWFTYPE 
      0 "NotAppl"
  /QWFREG  
      0 "NotAppl"
  /QWFEDUC 
      0 "NotAppl"
  /QWFWLTH 
      0 "NotAppl"
  /Q201    
      1 "Yes"
      2 "No"
  /Q202    
      1 "Yes"
      2 "No"
  /Q204    
      1 "Yes"
      2 "No"
  /Q206    
      1 "Yes"
      2 "No"
  /Q207A   
      1 "Yes"
      2 "No"
  /Q207C   
      1 "Yes"
      2 "No"
  /Q207E   
      1 "Yes"
      2 "No"
  /Q209    
      1 "Yes, is correct"
      2 "No, is not correct"
  /Q222    
      1 "Yes"
      2 "No"
  /Q224A   
      0 "None"
  /Q224AY  
      0 "None"
   2012 "2012"
   2013 "2013"
   2014 "2014"
   2015 "2015"
   2016 "2016"
   2017 "2017"
   9998 "DK year"
  /Q224B   
      0 "None"
  /Q224BY  
      0 "None"
   2012 "2012"
   2013 "2013"
   2014 "2014"
   2015 "2015"
   2016 "2016"
   2017 "2017"
   9998 "DK year"
  /Q224C   
      0 "None"
  /Q224D   
      0 "None"
  /Q226    
      1 "Yes"
      2 "No"
      8 "Unsure"
  /Q228    
      1 "Yes"
      2 "No"
  /Q229    
      1 "Later"
      2 "No more/none"
  /Q230U   
      1 "Days ago"
      2 "Weeks ago"
      3 "Months ago"
      4 "Years ago"
      9 "Special answers"
  /Q230N   
     94 "In menopause, has had hysterectomy"
     95 "Before last birth"
     96 "Never menstruated"
     98 "Don't know"
  /Q231    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q232    
      1 "Just before her period begins"
      2 "During her period"
      3 "Right after her period has ended"
      4 "Halfway between two periods"
      6 "Other"
      8 "Don't know"
  /Q233    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q227F   
      7 "Month - exact date"
      8 "None - imputed"
  /Q238F   
      1 "N > interval since birth"
      2 "N + amenorrhea > interval"
      3 "N, but period not returned"
      4 "95, but no birth"
      5 "95, but period returned"
      6 "96, but period returned"
      7 "N, last period in pregnancy"
      8 "96, had children"
      9 "N, period before last birth"
  /Q301N$01
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$02
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$03
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$04
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$05
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$06
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$07
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$08
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$09
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$10
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$11
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$12
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$13
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301N$14
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Emergency contraception"
     10 "Lactational amenorrhea method (LAM)"
     11 "Rhythm method"
     12 "Withdrawal"
     13 "Other modern method"
     14 "Other traditional method"
  /Q301$01 
      1 "Yes"
      2 "No"
  /Q301$02 
      1 "Yes"
      2 "No"
  /Q301$03 
      1 "Yes"
      2 "No"
  /Q301$04 
      1 "Yes"
      2 "No"
  /Q301$05 
      1 "Yes"
      2 "No"
  /Q301$06 
      1 "Yes"
      2 "No"
  /Q301$07 
      1 "Yes"
      2 "No"
  /Q301$08 
      1 "Yes"
      2 "No"
  /Q301$09 
      1 "Yes"
      2 "No"
  /Q301$10 
      1 "Yes"
      2 "No"
  /Q301$11 
      1 "Yes"
      2 "No"
  /Q301$12 
      1 "Yes"
      2 "No"
  /Q301$13 
      1 "Yes"
      2 "No"
  /Q301$14 
      1 "Yes"
      2 "No"
  /Q303    
      1 "Yes"
      2 "No"
  /Q304    
   'A               ' "Female sterilization"
   'B               ' "Male sterilization"
   'C               ' "IUD"
   'D               ' "Injectables"
   'E               ' "Implants"
   'F               ' "Pill"
   'G               ' "Condom"
   'H               ' "Female condom"
   'I               ' "Diaphragm"
   'J               ' "Foam/jelly"
   'K               ' "Emergency contraception"
   'L               ' "Lactational amenorrhea method (LAM)"
   'M               ' "Rhythm method"
   'N               ' "Withdrawal"
   'X               ' "Other modern method"
   'Y               ' "Other traditional method"
  /Q305    
      1 "Yes"
      2 "No"
  /Q306    
   'A                  ' "Public: Govt hospital"
   'B                  ' "Public: Govt health center/clinic"
   'C                  ' "Public: Govt health post/chps"
   'D                  ' "Public: Mobile clinic/outreach"
   'E                  ' "Public: Family planning clinic"
   'F                  ' "Public: Fieldworker"
   'G                  ' "Public: Other public sector"
   'H                  ' "Private: Hospital/clinic"
   'I                  ' "Private: Doctor"
   'J                  ' "Private: Mobile clinic/outreach"
   'K                  ' "Private: Pharmacy/chemist/drug store"
   'L                  ' "Private: Fieldworker"
   'M                  ' "Private: Fp/ppag clinic"
   'N                  ' "Private: Maternity home"
   'O                  ' "Private: Other private med sector"
   'P                  ' "Other source: Shop"
   'Q                  ' "Other source: Church"
   'R                  ' "Other source: Friend/relative"
   'X                  ' "Other"
  /Q304N   
      1 "Female Sterilization"
      2 "Male Sterilization"
      3 "IUD"
      4 "Injectables"
      5 "Implants"
      6 "Pill"
      7 "Condom"
      8 "Female condom"
      9 "Diaphragm"
     10 "Foam/jelly"
     11 "Emergency contraception"
     12 "Lactational amenorrhea method (LAM)"
     13 "Rhythm method"
     14 "Withdrawal"
     95 "Other modern method"
     96 "Other traditional method"
  /Q577$1  
      1 "Yes"
      2 "No"
  /Q577$2  
      1 "Yes"
      2 "No"
  /Q578$1  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q578$2  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q579$1  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q579$2  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q580$1  
   'A                  ' "Public: Govt hospital"
   'B                  ' "Public: Govt health center/clinic"
   'C                  ' "Public: Govt health post/chps"
   'D                  ' "Public: Mobile clinic/outreach"
   'E                  ' "Public: Family planning clinic"
   'F                  ' "Public: Fieldworker"
   'G                  ' "Public: Other public sector"
   'H                  ' "Private: Hospital/clinic"
   'I                  ' "Private: Doctor"
   'J                  ' "Private: Mobile clinic/outreach"
   'K                  ' "Private: Pharmacy/chemist/drug store"
   'L                  ' "Private: Fieldworker"
   'M                  ' "Private: Fp/ppag clinic"
   'N                  ' "Private: Maternity home"
   'O                  ' "Private: Other private med sector"
   'P                  ' "Other source: Shop"
   'Q                  ' "Other source: Church"
   'R                  ' "Other source: Friend/relative"
   'X                  ' "Other"
  /Q580$2  
   'A                  ' "Public: Govt hospital"
   'B                  ' "Public: Govt health center/clinic"
   'C                  ' "Public: Govt health post/chps"
   'D                  ' "Public: Mobile clinic/outreach"
   'E                  ' "Public: Family planning clinic"
   'F                  ' "Public: Fieldworker"
   'G                  ' "Public: Other public sector"
   'H                  ' "Private: Hospital/clinic"
   'I                  ' "Private: Doctor"
   'J                  ' "Private: Mobile clinic/outreach"
   'K                  ' "Private: Pharmacy/chemist/drug store"
   'L                  ' "Private: Fieldworker"
   'M                  ' "Private: Fp/ppag clinic"
   'N                  ' "Private: Maternity home"
   'O                  ' "Private: Other private med sector"
   'P                  ' "Other source: Shop"
   'Q                  ' "Other source: Church"
   'R                  ' "Other source: Friend/relative"
   'X                  ' "Other"
  /Q581$1  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q581$2  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q582$1  
   'A          ' "Rape/defilement"
   'B          ' "Incest"
   'C          ' "Life of mother in danger"
   'D          ' "Risk to physical health of mother"
   'E          ' "Risk to mental health of mother"
   'F          ' "Foetal abnormality"
   'G          ' "During first trimester only"
   'H          ' "Up to the second trimester"
   'I          ' "Mother mentally not sound"
   'J          ' "Not ready/to young/continue education"
   'K          ' "Financial problems/partner denies responsibility"
   'X          ' "Other"
   'Z          ' "Don't know"
  /Q582$2  
   'A          ' "Rape/defilement"
   'B          ' "Incest"
   'C          ' "Life of mother in danger"
   'D          ' "Risk to physical health of mother"
   'E          ' "Risk to mental health of mother"
   'F          ' "Foetal abnormality"
   'G          ' "During first trimester only"
   'H          ' "Up to the second trimester"
   'I          ' "Mother mentally not sound"
   'J          ' "Not ready/to young/continue education"
   'K          ' "Financial problems/partner denies responsibility"
   'X          ' "Other"
   'Z          ' "Don't know"
  /Q701    
      1 "Yes, currently married"
      2 "Yes, living with a man"
      3 "No, not in union"
  /Q702    
      1 "Yes, formerly married"
      2 "Yes, lived with a man"
      3 "No"
  /Q703    
      1 "Widowed"
      2 "Divorced"
      3 "Separated"
  /Q704    
      1 "Lives with her"
      2 "Staying elsewhere"
  /Q705    
      0 "Not listed in the household"
  /Q706    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q707    
     98 "Don't know"
  /Q709    
      1 "Only once"
      2 "More than once"
  /Q710M   
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     97 "Inconsistent"
     98 "Don't know month"
  /Q710Y   
   9997 "Inconsistent"
   9998 "Don't know year"
  /Q711    
     97 "Inconsistent"
  /Q713    
      0 "Never had sexual intercourse"
     97 "Refuse to answer"
  /Q714U   
      1 "Days ago"
      2 "Weeks ago"
      3 "Months ago"
      4 "Years ago"
  /Q710F   
      1 "Month and year"
      2 "Month and age -y imp"
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
  /Q713F   
      0 "No flag"
      1 "After interview"
      2 "After conception >= 1 yr"
      3 "After conception < 1 yr"
      4 "At marriage, never married"
      5 "At marriage, after conception"
      6 "After marriage"
  /Q714F   
      0 "No flag"
      1 "N > interval since birth"
      2 "N + abstinence > interval"
      3 "N, but sex not resumed"
      4 "96, but no birth"
      5 "96, but currently pregnant"
      6 "96, but resumed sex"
      7 "N, last sex before pregnancy"
      8 "N, inconsistent with sex in last 4 weeks"
      9 "N, sex before last birth"
  /Q814$01 
      1 "Male"
      2 "Female"
  /Q814$02 
      1 "Male"
      2 "Female"
  /Q814$03 
      1 "Male"
      2 "Female"
  /Q814$04 
      1 "Male"
      2 "Female"
  /Q814$05 
      1 "Male"
      2 "Female"
  /Q814$06 
      1 "Male"
      2 "Female"
  /Q814$07 
      1 "Male"
      2 "Female"
  /Q814$08 
      1 "Male"
      2 "Female"
  /Q814$09 
      1 "Male"
      2 "Female"
  /Q814$10 
      1 "Male"
      2 "Female"
  /Q814$11 
      1 "Male"
      2 "Female"
  /Q814$12 
      1 "Male"
      2 "Female"
  /Q814$13 
      1 "Male"
      2 "Female"
  /Q814$14 
      1 "Male"
      2 "Female"
  /Q814$15 
      1 "Male"
      2 "Female"
  /Q814$16 
      1 "Male"
      2 "Female"
  /Q814$17 
      1 "Male"
      2 "Female"
  /Q814$18 
      1 "Male"
      2 "Female"
  /Q814$19 
      1 "Male"
      2 "Female"
  /Q814$20 
      1 "Male"
      2 "Female"
  /Q815$01 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$02 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$03 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$04 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$05 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$06 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$07 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$08 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$09 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$10 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$11 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$12 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$13 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$14 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$15 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$16 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$17 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$18 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$19 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q815$20 
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q819$01 
      1 "Yes"
      2 "No"
  /Q819$02 
      1 "Yes"
      2 "No"
  /Q819$03 
      1 "Yes"
      2 "No"
  /Q819$04 
      1 "Yes"
      2 "No"
  /Q819$05 
      1 "Yes"
      2 "No"
  /Q819$06 
      1 "Yes"
      2 "No"
  /Q819$07 
      1 "Yes"
      2 "No"
  /Q819$08 
      1 "Yes"
      2 "No"
  /Q819$09 
      1 "Yes"
      2 "No"
  /Q819$10 
      1 "Yes"
      2 "No"
  /Q819$11 
      1 "Yes"
      2 "No"
  /Q819$12 
      1 "Yes"
      2 "No"
  /Q819$13 
      1 "Yes"
      2 "No"
  /Q819$14 
      1 "Yes"
      2 "No"
  /Q819$15 
      1 "Yes"
      2 "No"
  /Q819$16 
      1 "Yes"
      2 "No"
  /Q819$17 
      1 "Yes"
      2 "No"
  /Q819$18 
      1 "Yes"
      2 "No"
  /Q819$19 
      1 "Yes"
      2 "No"
  /Q819$20 
      1 "Yes"
      2 "No"
  /Q820$01 
      1 "Yes"
      2 "No"
  /Q820$02 
      1 "Yes"
      2 "No"
  /Q820$03 
      1 "Yes"
      2 "No"
  /Q820$04 
      1 "Yes"
      2 "No"
  /Q820$05 
      1 "Yes"
      2 "No"
  /Q820$06 
      1 "Yes"
      2 "No"
  /Q820$07 
      1 "Yes"
      2 "No"
  /Q820$08 
      1 "Yes"
      2 "No"
  /Q820$09 
      1 "Yes"
      2 "No"
  /Q820$10 
      1 "Yes"
      2 "No"
  /Q820$11 
      1 "Yes"
      2 "No"
  /Q820$12 
      1 "Yes"
      2 "No"
  /Q820$13 
      1 "Yes"
      2 "No"
  /Q820$14 
      1 "Yes"
      2 "No"
  /Q820$15 
      1 "Yes"
      2 "No"
  /Q820$16 
      1 "Yes"
      2 "No"
  /Q820$17 
      1 "Yes"
      2 "No"
  /Q820$18 
      1 "Yes"
      2 "No"
  /Q820$19 
      1 "Yes"
      2 "No"
  /Q820$20 
      1 "Yes"
      2 "No"
  /Q821$01 
      1 "Yes"
      2 "No"
  /Q821$02 
      1 "Yes"
      2 "No"
  /Q821$03 
      1 "Yes"
      2 "No"
  /Q821$04 
      1 "Yes"
      2 "No"
  /Q821$05 
      1 "Yes"
      2 "No"
  /Q821$06 
      1 "Yes"
      2 "No"
  /Q821$07 
      1 "Yes"
      2 "No"
  /Q821$08 
      1 "Yes"
      2 "No"
  /Q821$09 
      1 "Yes"
      2 "No"
  /Q821$10 
      1 "Yes"
      2 "No"
  /Q821$11 
      1 "Yes"
      2 "No"
  /Q821$12 
      1 "Yes"
      2 "No"
  /Q821$13 
      1 "Yes"
      2 "No"
  /Q821$14 
      1 "Yes"
      2 "No"
  /Q821$15 
      1 "Yes"
      2 "No"
  /Q821$16 
      1 "Yes"
      2 "No"
  /Q821$17 
      1 "Yes"
      2 "No"
  /Q821$18 
      1 "Yes"
      2 "No"
  /Q821$19 
      1 "Yes"
      2 "No"
  /Q821$20 
      1 "Yes"
      2 "No"
  /Q823$01 
      1 "Yes"
      2 "No"
  /Q823$02 
      1 "Yes"
      2 "No"
  /Q823$03 
      1 "Yes"
      2 "No"
  /Q823$04 
      1 "Yes"
      2 "No"
  /Q823$05 
      1 "Yes"
      2 "No"
  /Q823$06 
      1 "Yes"
      2 "No"
  /Q823$07 
      1 "Yes"
      2 "No"
  /Q823$08 
      1 "Yes"
      2 "No"
  /Q823$09 
      1 "Yes"
      2 "No"
  /Q823$10 
      1 "Yes"
      2 "No"
  /Q823$11 
      1 "Yes"
      2 "No"
  /Q823$12 
      1 "Yes"
      2 "No"
  /Q823$13 
      1 "Yes"
      2 "No"
  /Q823$14 
      1 "Yes"
      2 "No"
  /Q823$15 
      1 "Yes"
      2 "No"
  /Q823$16 
      1 "Yes"
      2 "No"
  /Q823$17 
      1 "Yes"
      2 "No"
  /Q823$18 
      1 "Yes"
      2 "No"
  /Q823$19 
      1 "Yes"
      2 "No"
  /Q823$20 
      1 "Yes"
      2 "No"
  /Q824$01 
      1 "Yes"
      2 "No"
  /Q824$02 
      1 "Yes"
      2 "No"
  /Q824$03 
      1 "Yes"
      2 "No"
  /Q824$04 
      1 "Yes"
      2 "No"
  /Q824$05 
      1 "Yes"
      2 "No"
  /Q824$06 
      1 "Yes"
      2 "No"
  /Q824$07 
      1 "Yes"
      2 "No"
  /Q824$08 
      1 "Yes"
      2 "No"
  /Q824$09 
      1 "Yes"
      2 "No"
  /Q824$10 
      1 "Yes"
      2 "No"
  /Q824$11 
      1 "Yes"
      2 "No"
  /Q824$12 
      1 "Yes"
      2 "No"
  /Q824$13 
      1 "Yes"
      2 "No"
  /Q824$14 
      1 "Yes"
      2 "No"
  /Q824$15 
      1 "Yes"
      2 "No"
  /Q824$16 
      1 "Yes"
      2 "No"
  /Q824$17 
      1 "Yes"
      2 "No"
  /Q824$18 
      1 "Yes"
      2 "No"
  /Q824$19 
      1 "Yes"
      2 "No"
  /Q824$20 
      1 "Yes"
      2 "No"
  /Q901A   
      1 "Big problem"
      2 "Not a big problem"
  /Q901B   
      1 "Big problem"
      2 "Not a big problem"
  /Q901C   
      1 "Big problem"
      2 "Not a big problem"
  /Q901D   
      1 "Big problem"
      2 "Not a big problem"
  /Q902    
      1 "Yes"
      2 "No"
  /Q903    
      1 "Yes"
      2 "No"
  /Q904    
   'A    ' "National/district health insurance (nhis)"
   'B    ' "Health insurance through employer"
   'C    ' "Mutual health organization/community-based health ins"
   'D    ' "Other privately purchased/commercial health insurance"
   'X    ' "Other"
  /Q905A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q905B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q905C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q905D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q905E   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q905F   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q906    
      1 "Yes, always"
      2 "Yes, sometimes"
      3 "No, never"
      8 "Don't know"
  /Q908    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q909A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q909B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q909C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q909D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q909E   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q911    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q912A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q912B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q912C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q912D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q912E   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q914    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q916    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q917    
      1 "Yes"
      2 "No"
  /Q918    
      1 "No difficulty"
      2 "Some difficulty"
      3 "A lot of difficulty"
      4 "Cannot at all"
      8 "Don't know"
  /Q919    
      1 "No difficulty"
      2 "Some difficulty"
      3 "A lot of difficulty"
      4 "Cannot at all"
      8 "Don't know"
  /Q920    
      1 "No difficulty"
      2 "Some difficulty"
      3 "A lot of difficulty"
      4 "Cannot at all"
      8 "Don't know"
  /Q921    
      1 "No difficulty"
      2 "Some difficulty"
      3 "A lot of difficulty"
      4 "Cannot at all"
      8 "Don't know"
  /Q922    
      1 "No difficulty"
      2 "Some difficulty"
      3 "A lot of difficulty"
      4 "Cannot at all"
      8 "Don't know"
  /Q923    
      1 "No difficulty"
      2 "Some difficulty"
      3 "A lot of difficulty"
      4 "Cannot at all"
      8 "Don't know"
  /Q924    
      1 "No difficulty"
      2 "Some difficulty"
      3 "A lot of difficulty"
      4 "Cannot at all"
      8 "Don't know"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\GH7I\GHIQ7IFL.sav'.
