DATA LIST FILE='C:\COUNTRIES\GH7I\GHVA7IFL_LAST5YEARS.DAT' RECORDS=1
  /
  QVHCLUST    1-4   
  QVHNUMBER    5-8   
  QLINE       9-10  
  QREGION    11-12  
  QDISTR     13-16  
  QINTD      17-18  
  QINTM      19-20  
  QINTY      21-24  
  QINTNUM    25-28  
  QRESULT    29-29  
  QVISITS    30-30  
  QSUPERV    31-34  
  QLANGQ     35-36  
  QLANGI     37-38  
  QLANGR     39-40  
  QTRANS     41-41  
  QINTC      42-45  
  QINTCD     46-50  
  QWEIGHT    51-58  
  QTYPE      59-59  
  QCONSENT   60-60  
  Q1007H     61-62  
  Q1007M     63-64  
  Q100H      65-66  
  Q100M      67-68  
  Q101D      69-70  
  Q101M      71-72  
  Q101Y      73-76  
  Q102D      77-78  
  Q102M      79-80  
  Q102Y      81-84  
  Q104       85-86  
  Q106       87-87  
  Q107       88-88  
  Q108A      89-89  
  Q108B      90-91  
  Q108C      92-92  
  Q108D      93-93  
  Q109       94-94  
  Q110       95-95  
  Q111       96-96  
  Q112       97-98  
  Q113       99-100 
  Q114      101-102 
  Q115      103-103 
  Q116      104-104 
  Q117      105-105 
  Q118      106-106 
  Q119      107-107 
  Q120      108-108 
  QELIG     109-109 
  Q101C     110-113 
  Q101F     114-114 
  Q102C     115-118 
  Q102F     119-119 
  Q201      120-120 
  Q102CD    121-125 
  Q102DI    126-127 
  Q301      128-128 
  Q302A     129-129 
  Q302B     130-130 
  Q302C     131-140  (A)
  Q303      141-141 
  Q304      142-142 
  Q305      143-143 
  Q306      144-144 
  Q307A     145-145 
  Q307B     146-146 
  Q307C     147-147 
  Q308      148-148 
  Q309      149-149 
  Q310      150-150 
  Q311      151-151 
  Q312      152-152 
  Q313      153-153 
  Q314      154-154 
  Q315      155-155 
  Q316      156-156 
  Q317      157-157 
  Q318      158-158 
  Q319      159-159 
  Q401AU    160-160 
  Q401AN    161-162 
  Q402      163-163 
  Q403      164-164 
  Q404U     165-165 
  Q404N     166-167 
  Q405A     168-168 
  Q405BU    169-169 
  Q405BN    170-171 
  Q406      172-172 
  Q407      173-173 
  Q408U     174-174 
  Q408N     175-176 
  Q409      177-177 
  Q410A     178-178 
  Q410BU    179-179 
  Q410BN    180-181 
  Q413      182-182 
  Q414U     183-183 
  Q414N     184-185 
  Q415      186-186 
  Q416U     187-187 
  Q416N     188-189 
  Q417      190-190 
  Q418U     191-191 
  Q418N     192-193 
  Q419      194-194 
  Q420U     195-195 
  Q420N     196-197 
  Q421      198-198 
  Q422U     199-199 
  Q422N     200-201 
  Q423      202-202 
  Q424U     203-203 
  Q424N     204-205 
  Q425      206-206 
  Q426      207-208 
  Q427U     209-209 
  Q427N     210-211 
  Q428      212-212 
  Q429U     213-213 
  Q429N     214-215 
  Q430      216-216 
  Q431U     217-217 
  Q431N     218-219 
  Q432      220-220 
  Q433U     221-221 
  Q433N     222-223 
  Q434      224-224 
  Q435      225-225 
  Q436U     226-226 
  Q436N     227-228 
  Q437      229-229 
  Q438U     230-230 
  Q438N     231-232 
  Q439      233-233 
  Q440U     234-234 
  Q440N     235-236 
  Q441      237-237 
  Q442U     238-238 
  Q442N     239-240 
  Q443      241-241 
  Q444U     242-242 
  Q444N     243-244 
  Q445      245-245 
  Q446      246-246 
  Q447U     247-247 
  Q447N     248-249 
  Q448      250-250 
  Q501A     251-251 
  Q501B     252-253 
  Q501C     254-254 
  Q501D     255-255 
  Q501E     256-256 
  Q501F     257-257 
  Q502A     258-258 
  Q502BU    259-259 
  Q502BN    260-261 
  Q502C     262-262 
  Q502D     263-263 
  Q502E     264-264 
  Q503A     265-265 
  Q503BU    266-266 
  Q503BN    267-268 
  Q503C     269-269 
  Q504A     270-270 
  Q504B     271-272 
  Q505A     273-273 
  Q505B     274-275 
  Q505C     276-276 
  Q505D     277-277 
  Q506      278-278 
  Q507A     279-279 
  Q507B     280-280 
  Q507C     281-282 
  Q507DU    283-283 
  Q507DN    284-285 
  Q508A     286-286 
  Q508B     287-288 
  Q508C     289-289 
  Q508D     290-290 
  Q509A     291-291 
  Q509B     292-292 
  Q509C     293-294 
  Q509D     295-295 
  Q509E     296-296 
  Q510      297-297 
  Q511A     298-298 
  Q511B     299-299 
  Q511CU    300-300 
  Q511CN    301-302 
  Q511D     303-303 
  Q512A     304-304 
  Q512BU    305-305 
  Q512BN    306-307 
  Q512C     308-308 
  Q513A     309-309 
  Q513BU    310-310 
  Q513BN    311-312 
  Q514      313-313 
  Q515A     314-314 
  Q515B     315-316 
  Q516A     317-317 
  Q516B     318-319 
  Q517A     320-320 
  Q517BU    321-321 
  Q517BN    322-323 
  Q518A     324-324 
  Q518B     325-325 
  Q518C     326-326 
  Q518D     327-327 
  Q519A     328-328 
  Q519B     329-330 
  Q519C     331-331 
  Q520A     332-332 
  Q520B     333-333 
  Q520C     334-334 
  Q520D     335-335 
  Q522A     336-336 
  Q522B     337-337 
  Q523A     338-338 
  Q523B     339-339 
  Q523C     340-341 
  Q524A     342-342 
  Q524B     343-344 
  Q524C     345-349  (A)
  Q525      350-350 
  Q526      351-351 
  Q527A     352-352 
  Q527B     353-353 
  Q528      354-354 
  Q529      355-355 
  Q530      356-356 
  Q531      357-357 
  Q532A     358-358 
  Q532B     359-360 
  Q533A     361-361 
  Q533B     362-363 
  Q533C     364-364 
  Q534      365-365 
  Q535A     366-366 
  Q535B     367-367 
  Q535C     368-368 
  Q535D     369-369 
  Q535E     370-370 
  Q536A     371-371 
  Q536B     372-372 
  Q536C     373-374 
  Q537A     375-375 
  Q537B     376-377 
  Q537C     378-378 
  Q538      379-379 
  Q539A     380-380 
  Q539B     381-382 
  Q540      383-383 
  Q541      384-384 
  Q542      385-385 
  Q601      386-386 
  Q602      387-387 
  Q603A     388-388 
  Q603B     389-389 
  Q603C     390-390 
  Q603E     391-391 
  Q603F     392-392 
  Q603G     393-393 
  Q603I     394-394 
  Q603J     395-396 
  Q604      397-397 
  Q605      398-398 
  Q606      399-399 
  Q608      400-400 
  Q608A     401-401 
  Q609      402-403 
  Q611      404-404 
  Q612A     405-405 
  Q612B     406-406 
  Q613      407-407 
  Q614      408-408 
  Q615      409-409 
  Q616B     410-410 
  Q617A     411-412 
  Q617C     413-413 
  Q618      414-414 
  Q619      415-415 
  Q620      416-416 
  Q621      417-417 
  Q622B     418-418 
  Q622C     419-419 
  Q622D     420-420 
  Q623A     421-421 
  Q623B     422-422 
  Q623C     423-423 
  Q623D     424-424 
  Q624      425-425 
  Q625      426-426 
  Q626      427-427 
  Q627      428-428 
  Q628      429-429 
  Q630      430-431 
  Q631      432-432 
  Q632      433-441  (A)
  Q633      442-442 
  Q634      443-443 
  Q635      444-444 
  Q636      445-445 
  Q637      446-446 
  Q638      447-447 
  Q639      448-448 
  Q640      449-450 
  Q701      451-451 
  Q702A     452-452 
  Q702B     453-457  (A)
  Q702C     458-459 
  Q801      460-460 
  Q802      461-461 
  Q803      462-462 
  Q804      463-463 
  Q805      464-464 
  Q806      465-465 
  Q807      466-466 
  Q808A     467-467 
  Q808B     468-468 
  Q809      469-469 
  Q810A     470-470 
  Q810B     471-486  (A)
  Q810C     487-487 
  Q811A     488-488 
  Q811B     489-489 
  Q812A     490-490 
  Q812B     491-491 
  Q812C     492-500  (A)
  Q813AD    501-502 
  Q813AM    503-504 
  Q813AY    505-508 
  Q813B     509-514  (2)
  Q814AD    515-516 
  Q814AM    517-518 
  Q814AY    519-522 
  Q814B     523-528  (2)
  Q815AD    529-530 
  Q815AM    531-532 
  Q815AY    533-536 
  Q815B     537-537 
  Q901A     538-538 
  Q901B     539-539 
  Q902A     540-540 
  Q902B     541-542 
  Q902C     543-545 
  Q903      546-546 
  Q904      547-547 
  Q905      548-548 
  Q906      549-551 
  Q907      552-552 
  Q908      553-553 
  Q909      554-554 
  Q910      555-555 
  Q1001A    556-556 
  Q1001B    557-557 
  Q1002AD   558-559 
  Q1002AM   560-561 
  Q1002AY   562-565 
  Q1002BD   566-567 
  Q1002BM   568-569 
  Q1002BY   570-573 
  Q1003A    574-574 
  Q1003B    575-575 
  Q1003C    576-576 
  Q1003D    577-577 
  Q1004A    578-578 
  Q1004B    579-579 
  Q1005D    580-581 
  Q1005M    582-583 
  Q1005Y    584-587 
  Q1006     588-588 
  CDICD10I  589-592  (A)
  CDDEATHP  593-593 
 .
VARIABLE LABELS
   QVHCLUST "Cluster number"
  /QVHNUMBER "Household number"
  /QLINE    "Individual line number"
  /QREGION  "Region"
  /QDISTR   "District"
  /QINTD    "Day of interview"
  /QINTM    "Month of interview"
  /QINTY    "Year of interview"
  /QINTNUM  "Interviewer number"
  /QRESULT  "Result of individual interview"
  /QVISITS  "Total number of visits"
  /QSUPERV  "Supervisor number"
  /QLANGQ   "Language of questionnaire"
  /QLANGI   "Language of interview"
  /QLANGR   "Language of respondent"
  /QTRANS   "Translator used"
  /QINTC    "Date of interview (CMC)"
  /QINTCD   "Date of interview Century Day Code (CDC)"
  /QWEIGHT  "Sample weight (6 decimals)"
  /QTYPE    "Type of place of residence"
  /QCONSENT "Consent agreement"
  /Q1007H   "End of interview (hour)"
  /Q1007M   "End of interview (minutes)"
  /Q100H    "Start of interview (hour)"
  /Q100M    "Start of interview (minutes)"
  /Q101D    "Day of birth"
  /Q101M    "Month of birth"
  /Q101Y    "Year of birth"
  /Q102D    "Day of death"
  /Q102M    "Month of death"
  /Q102Y    "Year of death"
  /Q104     "Age at death"
  /Q106     "Died while pregnant"
  /Q107     "Died during childbirth"
  /Q108A    "Died within 2 months of delivery"
  /Q108B    "Days after end of pregnancy/childbirth died"
  /Q108C    "Death due to violence"
  /Q108D    "Death due to accident"
  /Q109     "Marital status"
  /Q110     "Highest educational level attended"
  /Q111     "Work in last 12 months before died"
  /Q112     "Occupation"
  /Q113     "Religion"
  /Q114     "Ethnic group"
  /Q115     "Place of death"
  /Q116     "Usual place of residence"
  /Q117     "Place of burial"
  /Q118     "Season where she died"
  /Q119     "Relationship with main respondent"
  /Q120     "Living with respondent at period of death"
  /QELIG    "VA eligibility"
  /Q101C    "Date of birth (CMC)"
  /Q101F    "Date flag for Q101C"
  /Q102C    "Date of death (CMC)"
  /Q102F    "Date flag for Q102C"
  /Q201     "Description of events leading to death"
  /Q102CD   "Date of death Century Day Code (CDC)"
  /Q102DI   "Imputed day of death"
  /Q301     "Suffered from any injury or accident that led to death"
  /Q302A    "Road traffic accident"
  /Q302B    "Role in road traffic accident"
  /Q302C    "Counterpart during the road traffic accident"
  /Q303     "Injured in a non-road transport accident"
  /Q304     "Injured in a fall"
  /Q305     "Was there any poisoning"
  /Q306     "Die of drowning"
  /Q307A    "Injured by a bite or sting of venomous animal"
  /Q307B    "Injured by an animal or insect (non-venomous)"
  /Q307C    "Type of animal or insect"
  /Q308     "Injured by burns or fire"
  /Q309     "Subject to violence (suicide, homicide, or abuse)"
  /Q310     "Injured by a firearm"
  /Q311     "Stabbed, cut, or pierced"
  /Q312     "Strangled"
  /Q313     "Injured by a blunt force"
  /Q314     "Injured by a force of nature"
  /Q315     "Electrocuted"
  /Q316     "Injured by some other injury"
  /Q317     "Injury accidental"
  /Q318     "Accident or injury self-inflicted"
  /Q319     "Accident or injury intentionally inflicted by someone else"
  /Q401AU   "Length of illness before death (units)"
  /Q401AN   "Length of illness before death (number)"
  /Q402     "Die suddenly"
  /Q403     "Any diagnosis by a physician or health worker of tuberculosis or TB"
  /Q404U    "Months or years prior to death was diagnosed with tuberculosis or TB (units)"
  /Q404N    "Months or years prior to death was diagnosed with tuberculosis or TB (number)"
  /Q405A    "HIV test ever positive"
  /Q405BU   "Days, weeks or months prior to death was tested for HIV (units)"
  /Q405BN   "Days, weeks or months prior to death was tested for HIV (number)"
  /Q406     "Hiv test result"
  /Q407     "Any diagnosis by a physician or health worker of AIDS"
  /Q408U    "Months or years prior to death was diagnosed with AIDS (units)"
  /Q408N    "Months or years prior to death was diagnosed with AIDS (number)"
  /Q409     "Had a recent test by a physician or health worker for malaria"
  /Q410A    "Malaria test result"
  /Q410BU   "Days, weeks or months prior to death was tested with malaria (units)"
  /Q410BN   "Days, weeks or months prior to death was tested with malaria (number)"
  /Q413     "Any diagnosis by a physician or health worker of measles"
  /Q414U    "Months or years prior to death was diagnosed with measles (units)"
  /Q414N    "Months or years prior to death was diagnosed with measles (number)"
  /Q415     "Any diagnosis by a physician or health worker of high blood pressure"
  /Q416U    "Months or years prior to death was diagnosed with high blood pressure (units)"
  /Q416N    "Months or years prior to death was diagnosed with high blood pressure (number)"
  /Q417     "Any diagnosis by a physician or health worker of heart disease"
  /Q418U    "Months or years prior to death was diagnosed with heart disease (units)"
  /Q418N    "Months or years prior to death was diagnosed with heart disease (number)"
  /Q419     "Any diagnosis by a physician or health worker of diabetes"
  /Q420U    "Months or years prior to death was diagnosed with diabetes (units)"
  /Q420N    "Months or years prior to death was diagnosed with diabetes (number)"
  /Q421     "Any diagnosis by a physician or health worker of asthma"
  /Q422U    "Months or years prior to death was diagnosed with asthma (units)"
  /Q422N    "Months or years prior to death was diagnosed with asthma (number)"
  /Q423     "Any diagnosis by a physician or health worker of epilepsy"
  /Q424U    "Months or years prior to death was diagnosed with epilepsy (units)"
  /Q424N    "Months or years prior to death was diagnosed with epilepsy (number)"
  /Q425     "Any diagnosis by a physician or health worker of cancer"
  /Q426     "Type of cancer"
  /Q427U    "Months or years prior to death was diagnosed with cancer (units)"
  /Q427N    "Months or years prior to death was diagnosed with cancer (number)"
  /Q428     "Any diagnosis by a physician or health worker of chronic obstructive pulmonary disease (COPD)"
  /Q429U    "Months or years prior to death was diagnosed with chronic obstructive pulmonary disease (COPD) (units)"
  /Q429N    "Months or years prior to death was diagnosed with chronic obstructive pulmonary disease (COPD) (number)"
  /Q430     "Any diagnosis by a physician or health worker of dementia"
  /Q431U    "Months or years prior to death was diagnosed with dementia (units)"
  /Q431N    "Months or years prior to death was diagnosed with dementia (number)"
  /Q432     "Any diagnosis by a physician or health worker of depression"
  /Q433U    "Months or years prior to death was diagnosed with depression (units)"
  /Q433N    "Months or years prior to death was diagnosed with depression (number)"
  /Q434     "Any diagnosis by a physician or health worker of other mental disorder"
  /Q435     "Type of mental disorder"
  /Q436U    "Months or years prior to death was diagnosed with other mental disorder (units)"
  /Q436N    "Months or years prior to death was diagnosed with other mental disorder (number)"
  /Q437     "Any diagnosis by a physician or health worker of stroke"
  /Q438U    "Months or years prior to death was diagnosed with stroke (units)"
  /Q438N    "Months or years prior to death was diagnosed with stroke (number)"
  /Q439     "Any diagnosis by a physician or health worker of sickle cell disease"
  /Q440U    "Months or years prior to death was diagnosed with sickle cell disease (units)"
  /Q440N    "Months or years prior to death was diagnosed with sickle cell disease (number)"
  /Q441     "Any diagnosis by a physician or health worker of kidney disease"
  /Q442U    "Months or years prior to death was diagnosed with kidkey disease (units)"
  /Q442N    "Months or years prior to death was diagnosed with kidkey disease (number)"
  /Q443     "Any diagnosis by a physician or health worker of liver disease"
  /Q444U    "Months or years prior to death was diagnosed with liver disease (units)"
  /Q444N    "Months or years prior to death was diagnosed with liver disease (number)"
  /Q445     "Any diagnosis by a physician or health worker of other chronic illness"
  /Q446     "Type of illness"
  /Q447U    "Months or years prior to death was diagnosed with other chronic illness (units)"
  /Q447N    "Months or years prior to death was diagnosed with other chronic illness (number)"
  /Q448     "Cause of death"
  /Q501A    "Had a fever"
  /Q501B    "Duration of fever"
  /Q501C    "Fever continued until death"
  /Q501D    "Fever severity"
  /Q501E    "Pattern of the fever"
  /Q501F    "Had night sweats"
  /Q502A    "Had a cough"
  /Q502BU   "Cough duration (units)"
  /Q502BN   "Cough duration (number)"
  /Q502C    "Cough productive, with sputum"
  /Q502D    "Cough very severe"
  /Q502E    "Coughed up blood"
  /Q503A    "Had any difficulty breathing"
  /Q503BU   "Difficulty breathing duration (units)"
  /Q503BN   "Difficulty breathing duration (number)"
  /Q503C    "Difficulty continuous or on and off"
  /Q504A    "Had fast breathing during illness/events that led to death"
  /Q504B    "Duration of fast breathing"
  /Q505A    "Had breathlessness"
  /Q505B    "Duration of breathlessness"
  /Q505C    "Unabled to carry out daily routines due to breathlessness"
  /Q505D    "Breathless while lying flat"
  /Q506     "Breathing sound like wheezing during the illness/events that led to death"
  /Q507A    "Had chest pain"
  /Q507B    "Chest pain severe"
  /Q507C    "Duration of chest pain before death (days)"
  /Q507DU   "Duration of chest pain before death (units)"
  /Q507DN   "Duration of chest pain before death (number)"
  /Q508A    "Had more frequent loose or liquid stools than usual"
  /Q508B    "Duration of frequent loose or liquid stools"
  /Q508C    "Blood in the stools during final illness/events"
  /Q508D    "Blood in the stool up until death"
  /Q509A    "Vomited"
  /Q509B    "Vomited in the week preceding death"
  /Q509C    "Duration of vomiting  before death"
  /Q509D    "Vomited blood"
  /Q509E    "Vomited black"
  /Q510     "Had any belly (abdominal) problems"
  /Q511A    "Had any belly (abdominal) pain"
  /Q511B    "Belly (abdominal) pain severe"
  /Q511CU   "Duration of abdominal pain before death (units)"
  /Q511CN   "Duration of abdominal pain before death (number)"
  /Q511D    "Pain in the upper or lower abdomen"
  /Q512A    "Had more than usually protruding abdomen"
  /Q512BU   "Duration had a more than usually protruding abdomen (units)"
  /Q512BN   "Duration had a more than usually protruding abdomen (number)"
  /Q512C    "Speed of developing the protruding abdomen"
  /Q513A    "Had any mass in the abdomen"
  /Q513BU   "Duration had a mass in the abdomen before death (units)"
  /Q513BN   "Duration had a mass in the abdomen before death (number)"
  /Q514     "Had a severe headache"
  /Q515A    "Had a stiff neck during the illness/events that led to death"
  /Q515B    "Duration has a stiff neck before death"
  /Q516A    "Had a painful neck during the illness/events that led to death"
  /Q516B    "Duration had  painful neck before death"
  /Q517A    "Had mental confusion"
  /Q517BU   "Duration of mental confusion (units)"
  /Q517BN   "Duration of mental confusion (number)"
  /Q518A    "Unconscious during the illness/events that led to death"
  /Q518B    "Unconscious for more than 24 hours before death"
  /Q518C    "Unconsciousness start suddenly or quickly, at least within a single day"
  /Q518D    "Unconsciousness continue until death"
  /Q519A    "Had convulsions"
  /Q519B    "Duration of convulsions"
  /Q519C    "Became unconscious immediately after the convulsion"
  /Q520A    "Had any urine problems"
  /Q520B    "Stopped urinating"
  /Q520C    "Went to urinate more often than usual"
  /Q520D    "Ever passes blood in the urine"
  /Q522A    "Had sores"
  /Q522B    "Sores had clear fluid or pus"
  /Q523A    "Had an ulcer or pit on the foot"
  /Q523B    "Ulcer on the foot oozed pus"
  /Q523C    "Duration of the ulcer on the foot that oozed pus"
  /Q524A    "Had any skin rash during the illness/events that led to death"
  /Q524B    "Duration had the skin rash"
  /Q524C    "Place of the rash"
  /Q525     "Did she ever have shingles or herpes zoster?"
  /Q526     "Skin flaked off in patches during the illness/events that led to death,"
  /Q527A    "Bled from anywhere during the illness/events that led to death"
  /Q527B    "Bled from the mouth, nose, or anus"
  /Q528     "Had noticeable weight loss"
  /Q529     "Was severely thin or wasted"
  /Q530     "Had a whitish rash inside the mouth or on the tongue during the illness/events that led to death"
  /Q531     "Had stiffness of the whole body or was unable to open the mouth"
  /Q532A    "Had puffiness of the face"
  /Q532B    "Duration of puffiness of the face"
  /Q533A    "Had swollen legs or feet during the illness/events that led to death"
  /Q533B    "Duration of the swelling"
  /Q533C    "Had both feet swollen"
  /Q534     "Had  general puffiness all over her body"
  /Q535A    "Had any lumps"
  /Q535B    "Had any lumps or lesions in the mouth"
  /Q535C    "Had any lumps on the neck"
  /Q535D    "Had any lumps on the armpit"
  /Q535E    "Had any lumps on the groin"
  /Q536A    "Was in any way paralysed"
  /Q536B    "Had paralysis of only one side of the body"
  /Q536C    "Which were the limbs or body parts paralysed"
  /Q537A    "Had difficulty swallowing"
  /Q537B    "Duration of difficulty swallowing"
  /Q537C    "Difficulty with swallowing with solids, liquids, or both"
  /Q538     "Had pain upon swallowing"
  /Q539A    "Had yellow discoloration of the eyes"
  /Q539B    "Duration of yellow discoloration"
  /Q540     "Hair changed in colour to a reddish or yellowish colour"
  /Q541     "Looked pale (thinning/lack of blood) or have pale palms, eyes, or nail beds"
  /Q542     "Drank a lot more water than usual"
  /Q601     "Had any swelling or lump in the breast"
  /Q602     "Had any ulcers (pits) in the breast"
  /Q603A    "Ever had a period or menstruate"
  /Q603B    "Had vaginal bleeding in between menstrual periods"
  /Q603C    "Vaginal bleeding excessive"
  /Q603E    "Menstrual period stopped naturally because of menopause"
  /Q603F    "Had vaginal bleeding after cessation of menstruation"
  /Q603G    "Excessive vaginal bleeding in the week prior to death"
  /Q603I    "Period overdue at the time of death"
  /Q603J    "Duration of period overdue"
  /Q604     "Had a sharp pain in her abdomen shortly before death"
  /Q605     "Pregnant at the time of death"
  /Q606     "Died during or within 6 weeks of labour, delivery, abortion or miscarriage"
  /Q608     "Died less than 1 year after being pregnant or delivering a baby"
  /Q608A    "Confirmation: not pregnant and had not been pregnant or delivered in the 12 months before death"
  /Q609     "Duration of pregnancy"
  /Q611     "Died during labour or delivery"
  /Q612A    "Died after delivering a baby"
  /Q612B    "Died within 24 hours after delivery"
  /Q613     "Died within 6 weeks of childbirth"
  /Q614     "Gave birth to a live baby (within 6 weeks of death)"
  /Q615     "Died during or after a multiple pregnancy"
  /Q616B    "Breastfeeding the child in the days before death"
  /Q617A    "Births/stillbirths before this baby/pregnancy"
  /Q617C    "Had any previous caesarean section"
  /Q618     "During this pregnancy, suffered from high blood pressure"
  /Q619     "Had foul smelling vaginal discharge during pregnancy or after delivery"
  /Q620     "Bleeding while pregnant"
  /Q621     "Vaginal bleeding during the first 6 months of pregnancy"
  /Q622B    "During the last 3 months of pregnancy, suffered from convulsions"
  /Q622C    "During the last 3 months of pregnancy, suffered from blurred vision"
  /Q622D    "Vaginal bleeding during the last 3 months of pregnancy but before labour started"
  /Q623A    "Had excessive bleeding during labour or delivery"
  /Q623B    "Water broken before labour started or delivery"
  /Q623C    "Baby delivered less than 24 hours after water broke"
  /Q623D    "Water broke smell foul"
  /Q624     "Had excessive bleeding after delivery/miscarriage/abortion"
  /Q625     "Attempted to terminate the pregnancy"
  /Q626     "Had a recently pregnancy that ended in a miscarriage or abortion"
  /Q627     "Died during a miscarriage or abortion"
  /Q628     "Died within 6 weeks of having a miscarriage or abortion"
  /Q630     "Place she gave birth"
  /Q631     "Received professional assistance during the delivery"
  /Q632     "Person who delivered the baby"
  /Q633     "Had an operation to remove her uterus shortly before death because problems with labour/delivery"
  /Q634     "Delivery normal vaginal, without forceps or vacuum"
  /Q635     "Delivery vaginal, with forceps or vacuum"
  /Q636     "Delivery a caesarean section"
  /Q637     "Baby born more than one month early"
  /Q638     "Placenta completely delivered"
  /Q639     "Deliver or tried to deliver an abnormally positioned baby"
  /Q640     "Duration of labour"
  /Q701     "Drank alcohol at least once a week"
  /Q702A    "Used tobacco (Cigarette, cigar, pipe, etc.)"
  /Q702B    "Kind of tobacco used"
  /Q702C    "Amount of cigarettes smoked daily"
  /Q801     "Received any treatment for the illness/events/circumstances that led to her death"
  /Q802     "Received oral rehydration salts"
  /Q803     "Received (or needed) intravenous fluids (drip) treatment"
  /Q804     "Received (or needed) a blood transfusion"
  /Q805     "Received (or needed treatment/food through a tube passed through the nose"
  /Q806     "Receive (or needed) injectable antibiotics"
  /Q807     "Received  (or needed) antiretroviral therapy (ART)"
  /Q808A    "Had  (or needed) an operation for the illness/events"
  /Q808B    "Had the operation within 1 month before death"
  /Q809     "Discharged from hospital very ill"
  /Q810A    "Care sought outside the home while she had this illness/events"
  /Q810B    "Where was care sought"
  /Q810C    "Name or address of the main source of care"
  /Q811A    "Did a health care worker tell you the cause of death?"
  /Q811B    "What the health care worker said"
  /Q812A    "Had any health records that belonged to the deceased"
  /Q812B    "Health record seen"
  /Q812C    "Kind of health record provided"
  /Q813AD   "Day of the most recent (last) visit"
  /Q813AM   "Month of the most recent (last) visit"
  /Q813AY   "Year of the most recent (last) visit"
  /Q813B    "Weight written at the most recent (last) visit"
  /Q814AD   "Day of the last but one (second last) visit"
  /Q814AM   "Month of the last but one (second last) visit"
  /Q814AY   "Year of the last but one (second last) visit"
  /Q814B    "Weight written at the last but one (second last) visit"
  /Q815AD   "Day of the most recent (last) note"
  /Q815AM   "Month of the most recent (last) note"
  /Q815AY   "Year of the most recent (last) note"
  /Q815B    "Last note on health records"
  /Q901A    "Traveled to a hospital or health facility, in the final days before death"
  /Q901B    "Health facility name"
  /Q902A    "Used motorised transport to get to the hospital or health facility"
  /Q902B    "Main means of transport used to get to hospital/health facility"
  /Q902C    "Time to get to the health facility"
  /Q903     "Any problems in being received at the hospital or health facility"
  /Q904     "Any problems with the way she was treated in the hospital or health facility"
  /Q905     "Any problems getting medications or diagnostic tests in the hospital or health facility"
  /Q906     "Time to get to the nearest health facility"
  /Q907     "Any doubts about whether medical care was needed, in the final days before death"
  /Q908     "Traditional/herbal or spiritual medicine used, in the final days before death"
  /Q909     "Anyone used a telephone or cell phone to call for help, in the final days before death"
  /Q910     "Total costs of care and treatment prohibit other household payments,  over the course of illness/events"
  /Q1001A   "Had a death certificate"
  /Q1001B   "Can see the death certificate"
  /Q1002AD  "Day of death from death certificate"
  /Q1002AM  "Month of death from death certificate"
  /Q1002AY  "Year of death from death certificate"
  /Q1002BD  "Day of issue of death certificate"
  /Q1002BM  "Month of issue of death certificate"
  /Q1002BY  "Year of issue of death certificate"
  /Q1003A   "Cause of death from the first (top) line of death certificate"
  /Q1003B   "Cause of death from the second line of death certificate"
  /Q1003C   "Cause of death from the third line of death certificate"
  /Q1003D   "Cause of death from the fourth line of death certificate"
  /Q1004A   "Had a burial permit"
  /Q1004B   "Can see the burial permit"
  /Q1005D   "Day of issue of burial permit"
  /Q1005M   "Month of issue of burial permit"
  /Q1005Y   "Year of issue of burial permit"
  /Q1006    "Cause of death from the burial permit"
  /CDICD10I "ICD-10 Code (After application of m1-m4, final underlying cause of death)"
  /CDDEATHP "Death during pregnancy, childbirth, or within 42 days or 1 year of end of pregnancy?"
 .
VALUE LABELS
   QREGION 
      1 "Western"
      2 "Central"
      3 "Greater Accra"
      4 "Volta"
      5 "Eastern"
      6 "Ashanti"
      7 "Brong Ahafo"
      8 "Northern"
      9 "Upper East"
     10 "Upper West"
  /QINTM   
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
  /QRESULT 
      1 "Completed"
      2 "No household member at home or no competent respondent"
      3 "Entire household absent for extended period of time"
      4 "Postponed"
      5 "Refused"
      6 "Dwelling vacant or address not a dwelling"
      7 "Dwelling destroyed"
      8 "Dwelling not found"
      9 "Other"
  /QLANGQ  
      0 "English"
      1 "Akan"
      2 "Ga"
      3 "Ewe"
  /QLANGI  
      0 "English"
      1 "Akan"
      2 "Ga"
      3 "Ewe"
      4 "Guan"
      5 "Mole-dagbani"
      6 "Grusi"
      7 "Gurma"
      8 "Mande"
     96 "Other"
  /QLANGR  
      0 "English"
      1 "Akan"
      2 "Ga"
      3 "Ewe"
      4 "Guan"
      5 "Mole-dagbani"
      6 "Grusi"
      7 "Gurma"
      8 "Mande"
     96 "Other"
  /QTRANS  
      1 "Yes"
      2 "No"
  /QTYPE   
      1 "Urban"
      2 "Rural"
  /QCONSENT
      1 "Respondent agrees to be interviewed"
      2 "Respondent does not agree to be interviewed"
  /Q101D   
     98 "Don't know day"
  /Q101M   
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Don't know month"
  /Q102D   
     98 "Don't know day"
  /Q102M   
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Don't know month"
  /Q104    
     95 "95 or more"
  /Q106    
      1 "Yes"
      2 "No"
  /Q107    
      1 "Yes"
      2 "No"
  /Q108A   
      1 "Yes"
      2 "No"
  /Q108C   
      1 "Yes"
      2 "No"
  /Q108D   
      1 "Yes"
      2 "No"
  /Q109    
      1 "Never married"
      2 "Married"
      3 "Living with a partner"
      4 "Separated"
      5 "Divorced"
      6 "Widowed"
  /Q110    
      1 "Primary"
      2 "Middle"
      3 "Jss/jhs"
      4 "Secondary/Tech/Voc/Comm"
      5 "Sss/Shs/Tech/Voc/Comm"
      6 "Higher"
      7 "Never attended school"
      8 "Don't know"
  /Q111    
      1 "Yes"
      2 "No"
  /Q112    
      1 "Commissioned armed forces officers"
      2 "Non-commissioned armed forces officers"
      3 "Armed forces occupations, other ranks"
     11 "Chief executive, senior officers and legislators"
     12 "Administrative and commercial managers"
     13 "Production and specialized service managers"
     14 "Hospitality, retail and other services managers"
     21 "Science and engineering professionals"
     22 "Health professionals"
     23 "Teaching professionals"
     24 "Business and administrative professionals"
     25 "Information and communication technology professionals"
     26 "Legal, social and cultural professional"
     31 "Science and engineering associate professionals"
     32 "Health associate professionals"
     33 "Business and administration associate professionals"
     34 "Legal, social cultural and related associate professionals"
     35 "Information and communications technicians"
     41 "General and keyboard clerks"
     42 "Customer service clerks"
     43 "Numerical and mateial recording clerks"
     44 "Other clerical support workers"
     51 "Personal sales workers"
     52 "Sales workers"
     53 "Personal care workers"
     61 "Market-oriented agricultural workers"
     62 "Market-oriented skilled forestry, fishery and hunting workers"
     63 "Subsistence farmers, fishers, hunters and gatherers"
     71 "Building and related trades workers, excluding electricians"
     72 "Metal, machinery and related trades workers"
     73 "Handicraft and printing workers"
     74 "Electrical and electronic trades workers"
     75 "Food processing, wood working, garment and other craft and related trades workers"
     81 "Stationary plant and machine operators"
     82 "Assemblers"
     83 "Drivers and mobile plant operators"
     91 "Cleaners and helpers"
     92 "Agricultural, forestry and fishery labourers"
     93 "Labours in mining, construction, manufacturing and transport"
     94 "Food preparation assistants"
     95 "Street and related sales and service workers"
     96 "Refuse workers and other elementary workers"
     97 "Other occupations"
  /Q113    
      1 "Catholic"
      2 "Anglican"
      3 "Methodist"
      4 "Presbyterian"
      5 "Pentecostal/charismatic"
      6 "Other christian"
      7 "Islam"
      8 "Traditional/spiritualist"
      9 "No religion"
     96 "Other"
     98 "Don't know"
  /Q114    
      1 "Akan"
      2 "Ga/dangme"
      3 "Ewe"
      4 "Guan"
      5 "Mole-dagbani"
      6 "Grusi"
      7 "Gurma"
      8 "Mande"
     96 "Other"
  /Q115    
      1 "Her home"
      2 "Other home"
      3 "Health facility"
      4 "En route to health facility"
      5 "Shrine/prayer camp"
      6 "Other"
  /Q116    
      1 "In this house"
      2 "In this locality"
      3 "In a different village/town"
      6 "Other"
  /Q117    
      1 "In this house"
      2 "In this locality"
      3 "In a different village/town"
      4 "Burial not yet performed"
      6 "Other"
  /Q118    
      1 "Wet season"
      2 "Dry season"
      6 "Other"
  /Q119    
      1 "Husband/partner"
      2 "Parent"
      3 "Child"
      4 "Sibling"
      5 "Other family member"
      6 "Friend"
      7 "Another relationship"
  /Q120    
      1 "Yes"
      2 "No"
  /QELIG   
      1 "Eligible for VA"
      2 "Not eligible based on date of death"
      3 "Not eligible based on age of death"
  /Q101F   
      0 "Ruled ineligible for survey"
      1 "Month and year"
      2 "Month and age -y imp"
      3 "Year and age - m imp"
      4 "Y & age - y ignored"
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
  /Q102F   
      0 "Ruled ineligible for survey"
      1 "M of death and Y of death"
      2 "Y of death, Age of Death, Y of Birth, M of Birth - M of death imputed"
      3 "Y of death, Age of death, Year of birth - M of death imputed"
      4 "Y of death, Age of death, M of birth - M of death imputed"
      5 "Y of death, Age of death - M of death imputed"
      6 "Y of deah - M of death imputed"
      7 "None - Y of death, M of death imputed"
      8 "Other"
  /Q201    
      6 "Narrative events"
  /Q301    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q302A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q302B   
      1 "Pedestrian"
      2 "Driver or passenger in car or light vehicle"
      3 "Driver or passenger in bus or heavy vehicle"
      4 "Driver or passenger on motorcycle"
      5 "Driver or passenger on pedal cycle"
      6 "Other"
      8 "Don't know"
  /Q302C   
   'A         ' "Pedestrian"
   'B         ' "Stationary object"
   'C         ' "Car or light vehicle"
   'D         ' "Bus or heavy vehicle"
   'E         ' "Motorcycle"
   'F         ' "Pedal cycle"
   'H         ' "Ditch/verge/side of road"
   'I         ' "Road surface"
   'X         ' "Other"
   'Y         ' "Don't know"
  /Q303    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q304    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q305    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q306    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q307A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q307B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q307C   
      1 "Dog"
      2 "Snake"
      3 "Insect"
      4 "Scorpion"
      6 "Other"
      8 "Don't know"
  /Q308    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q309    
      1 "Yes, suicide"
      2 "Yes, homicide"
      3 "Yes, abuse"
      4 "No"
      8 "Don't know"
  /Q310    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q311    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q312    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q313    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q314    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q315    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q316    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q317    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q318    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q319    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q401AU  
      1 "Days"
      2 "Weeks"
      3 "Months"
      4 "Years"
  /Q401AN  
     95 "95 or more"
  /Q402    
      1 "Yes"
      2 "No"
  /Q403    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q404U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q404N   
     95 "95 or more"
     98 "Don't know"
  /Q405A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q405BU  
      1 "Days"
      2 "Weeks"
      3 "Months"
      9 "Special answers"
  /Q405BN  
     95 "95 or more"
     98 "Don't know"
  /Q406    
      1 "Positive"
      2 "Negative"
      8 "Don't know"
  /Q407    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q408U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q408N   
     95 "95 or more"
     98 "Don't know"
  /Q409    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q410A   
      1 "Positive"
      2 "Negative"
      8 "Don't know"
  /Q410BU  
      1 "Days"
      2 "Weeks"
      3 "Months"
      9 "Special answers"
  /Q410BN  
     95 "95 or more"
     98 "Don't know"
  /Q413    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q414U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q414N   
     95 "95 or more"
     98 "Don't know"
  /Q415    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q416U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q416N   
     95 "95 or more"
     98 "Don't know"
  /Q417    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q418U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q418N   
     95 "95 or more"
     98 "Don't know"
  /Q419    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q420U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q420N   
     95 "95 or more"
     98 "Don't know"
  /Q421    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q422U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q422N   
     95 "95 or more"
     98 "Don't know"
  /Q423    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q424U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q424N   
     95 "95 or more"
     98 "Don't know"
  /Q425    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q426    
     11 "Lung"
     12 "Breast"
     13 "Cervix"
     14 "Liver"
     15 "Throat"
     16 "Colon"
     96 "Other"
     98 "Don't know"
  /Q427U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q427N   
     95 "95 or more"
     98 "Don't know"
  /Q428    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q429U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q429N   
     95 "95 or more"
     98 "Don't know"
  /Q430    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q431U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q431N   
     95 "95 or more"
     98 "Don't know"
  /Q432    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q433U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q433N   
     95 "95 or more"
     98 "Don't know"
  /Q434    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q435    
      1 "Bipolar disorder"
      2 "Schizophrenia"
      6 "Other"
      8 "Don't know"
  /Q436U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q436N   
     95 "95 or more"
     98 "Don't know"
  /Q437    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q438U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q438N   
     95 "95 or more"
     98 "Don't know"
  /Q439    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q440U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q440N   
     95 "95 or more"
     98 "Don't know"
  /Q441    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q442U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q442N   
     95 "95 or more"
     98 "Don't know"
  /Q443    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q444U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q444N   
     95 "95 or more"
     98 "Don't know"
  /Q445    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q446    
      1 "Lupus"
      2 "Rheumatoid arthritis"
      6 "Other"
      8 "Don't know"
  /Q447U   
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q447N   
     95 "95 or more"
     98 "Don't know"
  /Q448    
      6 "Cause of death"
  /Q501A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q501B   
     95 "95 or more"
     98 "Don't know"
  /Q501C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q501D   
      1 "Mild"
      2 "Moderate"
      3 "Severe"
  /Q501E   
      1 "Continuous"
      2 "On and off"
      3 "Only at night"
      4 "Only during day"
      8 "Don't know"
  /Q501F   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q502A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q502BU  
      1 "Days"
      2 "Months"
      3 "Years"
      9 "Special answers"
  /Q502BN  
     95 "95 or more"
     98 "Don't know"
  /Q502C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q502D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q502E   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q503A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q503BU  
      1 "Days"
      2 "Months"
      3 "Years"
      9 "Special answers"
  /Q503BN  
     95 "95 or more"
     98 "Don't know"
  /Q503C   
      1 "Continuous"
      2 "On and off"
      8 "Don't know"
  /Q504A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q504B   
     95 "95 or more"
     98 "Don't know"
  /Q505A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q505B   
     95 "95 or more"
     98 "Don't know"
  /Q505C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q505D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q506    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q507A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q507B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q507C   
     95 "95 or more"
     98 "Don't know"
  /Q507DU  
      1 "Minutes"
      2 "Hours"
      9 "Special answers"
  /Q507DN  
     95 "95 or more"
     98 "Don't know"
  /Q508A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q508B   
     95 "95 or more"
     98 "Don't know"
  /Q508C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q508D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q509A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q509B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q509C   
     95 "95 or more"
     98 "Don't know"
  /Q509D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q509E   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q510    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q511A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q511B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q511CU  
      1 "Hours"
      2 "Days"
      3 "Weeks"
      4 "Months"
      9 "Special answers"
  /Q511CN  
     95 "95 or more"
     98 "Don't know"
  /Q511D   
      1 "Upper abdomen"
      2 "Lower abdomen"
      3 "Upper and lower abdomen"
      8 "Don't know"
  /Q512A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q512BU  
      1 "Days"
      2 "Months"
      9 "Special answers"
  /Q512BN  
     95 "95 or more"
     98 "Don't know"
  /Q512C   
      1 "Rapidly"
      2 "Slowly"
      8 "Don't know"
  /Q513A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q513BU  
      1 "Days"
      2 "Months"
      9 "Special answers"
  /Q513BN  
     95 "95 or more"
     98 "Don't know"
  /Q514    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q515A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q515B   
     95 "95 or more"
     98 "Don't know"
  /Q516A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q516B   
     95 "95 or more"
     98 "Don't know"
  /Q517A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q517BU  
      1 "Months"
      2 "Years"
      9 "Special answers"
  /Q517BN  
     95 "95 or more"
     98 "Don't know"
  /Q518A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q518B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q518C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q518D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q519A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q519B   
     95 "95 or more"
     98 "Don't know"
  /Q519C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q520A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q520B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q520C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q520D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q522A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q522B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q523A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q523B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q523C   
     95 "95 or more"
     98 "Don't know"
  /Q524A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q524B   
     95 "95 or more"
     98 "Don't know"
  /Q524C   
   'A    ' "Face/head"
   'B    ' "Trunk or abdomen"
   'C    ' "Extremities"
   'D    ' "Everywhere"
   'Y    ' "Don't know"
  /Q525    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q526    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q527A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q527B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q528    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q529    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q530    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q531    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q532A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q532B   
     95 "95 or more"
     98 "Don't know"
  /Q533A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q533B   
     95 "95 or more"
     98 "Don't know"
  /Q533C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q534    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q535A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q535B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q535C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q535D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q535E   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q536A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q536B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q536C   
      1 "Right side of body"
      2 "Left side of body"
      3 "Lower part of body"
      4 "Upper part of body"
      5 "One leg only"
      6 "One arm only"
      7 "Whole body"
      8 "Other"
     98 "Don't know"
  /Q537A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q537B   
     95 "95 or more"
     98 "Don't know"
  /Q537C   
      1 "Solids"
      2 "Liquids"
      3 "Both"
      8 "Don't know"
  /Q538    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q539A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q539B   
     95 "95 or more"
     98 "Don't know"
  /Q540    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q541    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q542    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q601    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q602    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q603A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q603B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q603C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q603E   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q603F   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q603G   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q603I   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q603J   
     95 "95 or more"
     98 "Don't know"
  /Q604    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q605    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q606    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q608    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q608A   
      1 "Yes, no pregnancy in 12 months before death"
      2 "No"
      8 "Don't know"
  /Q609    
     98 "Don't know"
  /Q611    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q612A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q612B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q613    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q614    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q615    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q616B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q617A   
     98 "Don't know"
  /Q617C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q618    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q619    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q620    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q621    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q622B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q622C   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q622D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q623A   
      1 "Yes"
      2 "No"
      3 "NA-Labour never started"
      8 "Don't know"
  /Q623B   
      1 "Before labour started"
      2 "During labour"
      3 "NA-Water never broke"
      8 "Don't know"
  /Q623C   
      1 "Less than 24 hours"
      2 "More than 24 hours"
      3 "NA-Baby never delivered"
      8 "Don't know"
  /Q623D   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q624    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q625    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q626    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q627    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q628    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q630    
     11 "Govt hospital"
     12 "Govt health center/clinic"
     13 "Govt health post/chps"
     14 "Mobile clinic/outreach"
     16 "Other public sector"
     21 "Private hospital/clinic"
     22 "Fp/ppag clinic"
     23 "Mobile clinic/outreach"
     24 "Maternity home"
     26 "Other private medical sector"
     31 "Deceased woman's home"
     32 "Other home"
     33 "TBA's home"
     96 "Other"
  /Q631    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q632    
   'A        ' "Doctor"
   'B        ' "Nurse/midwife"
   'C        ' "Com  health officer/nurse"
   'D        ' "Traditional birth attendant"
   'E        ' "Village health volunteer"
   'F        ' "Traditional health practitioner"
   'G        ' "Relative/friend"
   'X        ' "Other"
   'Y        ' "No one assisted"
  /Q633    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q634    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q635    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q636    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q637    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q638    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q639    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q640    
     95 "95 or more"
     96 "Never in labour"
     98 "Don't know"
  /Q701    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q702A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q702B   
   'A    ' "Cigarettes"
   'B    ' "Pipe"
   'C    ' "Chewing tobacco"
   'D    ' "Snuff"
   'Y    ' "Don't know"
  /Q702C   
     80 "80 or more"
     98 "Don't know"
  /Q801    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q802    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q803    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q804    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q805    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q806    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q807    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q808A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q808B   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q809    
      1 "Yes"
      2 "No"
      3 "Never admitted"
      4 "Never discharged"
      8 "Don't know"
  /Q810A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q810B   
   'A               ' "Govt hospital"
   'B               ' "Govt health center/clinic"
   'C               ' "Govt health post/chps"
   'D               ' "Mobile clinic/outreach"
   'E               ' "Other public sector"
   'F               ' "Private hospital/clinic"
   'G               ' "Fp/ppag clinic"
   'H               ' "Mobile clinic/outreach"
   'I               ' "Maternity home"
   'J               ' "Pharmacy/chemist/drug store"
   'K               ' "Other private medical sector"
   'L               ' "Deceased woman's home"
   'M               ' "Other home"
   'N               ' "TBA's home"
   'O               ' "Prayer camp/shrine"
   'X               ' "Other"
  /Q810C   
      6 "Name or address of health facility"
  /Q811A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q811B   
      6 "Health worker said"
  /Q812A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q812B   
      1 "Yes"
      2 "No"
  /Q812C   
   'A        ' "Maternal health book"
   'B        ' "Prescription form"
   'C        ' "Treatment cards"
   'D        ' "Discharge form"
   'E        ' "Laboratory results"
   'F        ' "Patient folder"
   'G        ' "Imaging/scan"
   'H        ' "Insurance form"
   'X        ' "Other"
  /Q813AD  
     98 "Day not recorded"
  /Q813AM  
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Month not recorded"
  /Q813AY  
   9998 "Year not recorded"
  /Q813B   
   999.98 "Weight not recorded"
  /Q814AD  
     96 "No second last visit"
     98 "Day not recorded"
  /Q814AM  
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Month not recorded"
  /Q814AY  
   9998 "Year not recorded"
  /Q814B   
   999.98 "Weight not recorded"
  /Q815AD  
     96 "No note"
     98 "Day not recorded"
  /Q815AM  
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Month not recorded"
  /Q815AY  
   9998 "Year not recorded"
  /Q815B   
      6 "Last note on health records"
  /Q901A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q901B   
      1 "Name"
      8 "Don't know"
  /Q902A   
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q902B   
     11 "Shared taxi"
     12 "Individual taxi"
     13 "Trotro"
     14 "Bus (metro mass)"
     15 "Private car"
     16 "Train"
     17 "Motorcycle"
     18 "Canoe/boat/ferry with motor"
     19 "Ambulance"
     20 "Canoe/boat/ferry, no motor"
     21 "Bicycle"
     22 "On foot"
     96 "Other"
     98 "Don't know"
  /Q902C   
    995 "995 or more minutes"
    998 "Don't know"
  /Q903    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q904    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q905    
      1 "Yes"
      2 "No"
      3 "NA-Dead on arrival"
      8 "Don't know"
  /Q906    
    995 "995 or more minutes"
    998 "Don't know"
  /Q907    
      1 "Yes, there were doubts"
      2 "No doubts-illness not serious"
      3 "No doubts-death inevitable"
      4 "No doubts-went to facility"
      5 "No doubts-not sick before death"
      8 "Don't know"
  /Q908    
      1 "Yes, traditional/herbal only"
      2 "Yes, spiritual only"
      3 "Yes, both"
      4 "No"
      8 "Don't know"
  /Q909    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q910    
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q1001A  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q1001B  
      1 "Yes"
      2 "No"
  /Q1002AD 
     98 "Day not recorded"
  /Q1002AM 
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Month not recorded"
  /Q1002AY 
   9998 "Year not recorded"
  /Q1002BD 
     98 "Day not recorded"
  /Q1002BM 
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Month not recorded"
  /Q1002BY 
   9998 "Year not recorded"
  /Q1003A  
      6 "Cause of death (first line)"
  /Q1003B  
      6 "Cause of death (second line)"
  /Q1003C  
      6 "Cause of death (third line)"
  /Q1003D  
      6 "Cause of death (fourth line)"
  /Q1004A  
      1 "Yes"
      2 "No"
      8 "Don't know"
  /Q1004B  
      1 "Yes"
      2 "No"
  /Q1005D  
     98 "Day not recorded"
  /Q1005M  
      1 "January"
      2 "February"
      3 "March"
      4 "April"
      5 "May"
      6 "June"
      7 "July"
      8 "August"
      9 "September"
     10 "October"
     11 "November"
     12 "December"
     98 "Month not recorded"
  /Q1005Y  
   9998 "Year not recorded"
  /Q1006   
      6 "Cause of death from the burial permit"
  /CDDEATHP
      1 "No, death not during pregnancy, childbirth, or 42 days or 1 year of end of pregnancy"
      2 "Yes, during pregnancy"
      3 "Yes, during childbirth"
      4 "Yes, within 42 days of end of pregnancy"
      5 "Yes, between 43 days and 1 year of end of pregnancy"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\GH7I\GHVA7IFL_LAST5YEARS.sav'.
